### ISSUE TITLE
Node: crash on for-of in async function

### ISSUE THREAD

**Issue by wmertens** [babel/babel-preset-env#103]
When I use target `node: 'current'`, I get this crash on transpile (both for Node 6.9 and 7.1):

```
Module build failed: Error: /project/lib/database/DB.js: unknown Statement of type "ForOfStatement"
    at /project/node_modules/regenerator-transform/lib/emit.js:657:15
...
```

I presume this is similar to https://github.com/facebook/regenerator/issues/229, and indeed when I manually add the plugin `babel-plugin-transform-es2015-for-of` things work again.

So either the `for-of` transform should stay enabled, `regenerator-transform` should handle `for-of`, or there should be one that only changes `for-of` inside async functions.

This is the debug configuration:
```
babel-preset-env: `DEBUG` option

Using targets: {
  "node": "current"
}

modules transform: commonjs

Using plugins:

 transform-exponentiation-operator {}

 transform-async-to-generator {}

 syntax-trailing-function-commas {}

Using polyfills:

 es6.weak-map {}

 es6.weak-set {}

 es6.reflect.apply {}

 es6.reflect.construct {}

 es6.reflect.define-property {}

 es6.reflect.delete-property {}

 es6.reflect.get {}

 es6.reflect.get-own-property-descriptor {}

 es6.reflect.get-prototype-of {}

 es6.reflect.has {}

 es6.reflect.is-extensible {}

 es6.reflect.own-keys {}

 es6.reflect.prevent-extensions {}

 es6.reflect.set {}

 es6.reflect.set-prototype-of {}

 es6.symbol {}

 es6.regexp.flags {}

 es7.array.includes.js {}

 es7.string.pad-start {}

 es7.string.pad-end {}
```

**Comment by hzoo** [comment]
This is weird to me because if you are using node 6 then you already have generator support so async -> generators shouldn't be using regenerator at all..

**Comment by wmertens** [comment]
@hzoo So it's a bug in transform-async-to-generator? Or should a different plugin be used there?

**Comment by hzoo** [comment]
It would be helpful to get the code so I can repro locally and see what the issue is

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
