### ISSUE TITLE
Promise seems to be polyfilled in environments that support promises

### ISSUE THREAD

**Issue by matthewmueller** [babel/babel-preset-env#105]
Just messing around with the new polyfill stuff, but not sure it's working for promises. Here's my `.babelrc`:

```json5
{
  "presets": [
    [ "env", { loose: true, modules: false, useBuiltins: true, targets: { chrome: 55 } } ],
    [ "react" ]
  ],
  "plugins": [
    "transform-runtime",
    "transform-class-properties",
    ["transform-react-jsx", { "pragma": "h" }]
  ]
}
```

Here's my file:

```js
export default class Callout extends Component {

  construct () {
    new Promise((reject, resolve) => {
      resolve('hi!')
    })
  }

  render () {
    return (
      <div>hello world!</div>
    )
  }
}
```

And here's my output (from `babel index.js`):

```js
import _Promise from 'babel-runtime/core-js/promise';

export default class Callout extends Component {

  construct() {
    new _Promise((reject, resolve) => {
      resolve('hi!');
    });
  }

  render() {
    return h(
      'div',
      null,
      'hello world!'
    );
  }
}
```

Based on the data, Promises have been supported since chrome 51. 

It's doing something though, because it's not polyfilling classes, and if I change it to `{ ie: 8 }`, it'll include a bunch more deps.

**Comment by hzoo** [comment]
babel-preset-env doesn't do anything to transform-runtime right now. That's why it's always being transformed (not polyfilled). You need to use babel-polyfill if you want to take advantage of it atm.

**Comment by matthewmueller** [comment]
@hzoo interesting, so do you know why the transforms do change based on the target in `babel-preset-env`?
