### ISSUE TITLE
[Question] how to use with babili?

### ISSUE THREAD

**Issue by Bnaya** [babel/babel-preset-env#110]
how my preset should look like if i want to merge babel-preset-env +  babili ?
And imo its make sense to make babili integrate into this preset as a flag

**Comment by GitScrum** [comment]
Hi @Bnaya see my confit in [post-config](https://github.com/post-org/post-config/blob/master/package.json)

**Comment by yavorsky** [comment]
@Bnaya babel-preset-env is a just preset like any others, so you are feel free to add other presets to your config and use them in conjunction.
Both the @GitScrum's example in package.json or .babelrc it might be like:

```
{
  presets: [
    ["env",
      {
        "targets": {
          node: "current",
          browsers: 'last 2 chrome versions, ie 10'
        }
      },
    ],
    "babili",
    "react",
    ...
  ]
}
```


Moreover you can add some plugins from preset-env to [exclude](https://github.com/babel/babel-preset-env#exclude) if you want to [prevent conflicts](https://github.com/babel/babel-preset-env/issues/60) with plugins specified apart.

**Comment by Bnaya** [comment]
I will loot intoit!

Thanks!
