### ISSUE TITLE
[Question] get rid of defaultInclude

### ISSUE THREAD

**Issue by laszbalo** [babel/babel-preset-env#111]
Trying to get rid of all the unused polyfills that env includes in my code. I have found that there are three polyfills which are always included no matter what and weigh ~35KB uncompressed. These are:

1. web.timers
2. web.immidiate
3. web.dom.iterable

I'd like to remove them and include them only if they are needed, but first, is there any particular reason, why are they always in the bundle?
With thanks,
Laszlo

**Comment by yavorsky** [comment]
Hi, @laszbalo! As well as for presets/plugins, [exclude](https://github.com/babel/babel-preset-env#exclude) option is useful to get rid of built-ins you don't need.

Ex: 
*.babelrc*
```
{
  presets: [
    ["env",
      {
        "targets": {
          browsers: 'last 2 chrome versions, ie 10'
        },
        exclude: ["web.timers", "web.immediate", "web.dom.iterable"],
        "useBuiltIns": true
      }
    ]
  ]
}
```
will ignore mentioned plugins.

**Comment by yavorsky** [comment]
> is there any particular reason, why are they always in the bundle?

I think, for now, there is no way to find out what environments are supporting this features, so it's always included as default built-ins regardless of the environment.

**Comment by laszbalo** [comment]
@yavorsky Thanks for your reply. My problem with _exclude_, that it **always** excludes the listed polyfills, which is not what I want. I only want to include polyfills when the target platform does not have a specific feature implemented natively **and** I actually use that feature. #84 is discussing this very problem. I came to a conclusion that automatically detecting what features are used are not possible with 100% accuracy therefore I am about to implement a very simple solution where I list the used features and having babel-preset-env to include only the minimum set of polyfills. Reading through the code, I spotted out that there is an [array](https://github.com/babel/babel-preset-env/blob/d6822f58e95c532bbfe0afdd9b140bc3967859f9/src/index.js#L15), which makes sure that the above polyfills are always included, which just seems unnecessary. I hoped that I get some insight what made the author to always include those.

**Comment by laszbalo** [comment]
I had some time and extracted out three test cases from core-js for the above modules. I could run them on something like Sauce Labs or BrowserStack to generate stats for each supported browsers and based on that we will have the data we need to decide upfront if those polyfills are needed. I could run these tests whenever a new version of the supported browsers will be released. However I haven't got an account with those services, therefore I would prefer adding the tests to an existing test suite, if there is one available. I need to do some research on this.

These are the total sizes of the modules from core-js in Chrome 55:
with defaultInclude: 23.2kB
without defaultInclude: 8.81kB

As a sidenote:
At its current form babel-preset-env includes the following polyfills for Chrome 55 on top of those in defaultInclude:
es7.string.pad-start
es7.string.pad-end
A made the small change that I mentioned in my previous comment in babel-preset-env, and because I am not using neither es7.string.pad-start nor es7.string.pad-end in my code, there is not a single byte from core-js is included in my bundle for the latest Chrome.

**Comment by hzoo** [comment]
I didn't think about it much earlier but wanted to be able to provide the same functionality as babel-polyfill by itself which included those 3. So yeah I think we would want to get the data for it somehow but otherwise you can exclude them.
