### ISSUE TITLE
Failing to replace `babel-preset-es2015` by `babel-preset-env`

### ISSUE THREAD

**Issue by Spy-Seth** [babel/babel-preset-env#122]
I'm replacing the usage of the `es2015` preset by this `env` preset on one of my node application but I'm facing some weird behavior. Not sure is that's a bug or my that make a mistake.

The doc said: 
> Default behavior without options is the same as babel-preset-latest

So I replace my `es2015` preset by this one in my `.babelrc` without specifing any options. Everything keep working in my app. 

The next step was to specify the target in the options: `["env", { "targets": { "node": "current" }}],`. Now my app failed to start with a lots of weird errors. After digging into this it seems that some of the `es2015` transformer are missing... The `transform-es2015-classes` and the `transform-es2015-destructuring`. When I force their activation, everything works again.

Here my `.babelrc`:

```js
{
    "presets": [
        ["env", {
            "targets": {
                "node": "current"
            },
            "include": [
                "transform-es2015-classes",
                "transform-es2015-destructuring",
                "transform-regenerator" // This one is not concerned by this issue
            ],
            "useBuiltIns": true
        }],
        "stage-1",
        "react"
    ],
    "env": {
        "development": {
            "plugins": ["transform-react-jsx-source"]
        },
        "testing": {
            "plugins": ["transform-react-jsx-source"]
        },
        "production": {
            "plugins": ["transform-react-constant-elements"]
        }
    }
}
```

I'm running on node LTS v6.9.2.

**Comment by yavorsky** [comment]
@Spy-Seth Seems like your node.js version already supports classes and destructuring, so these plugins aren't included. See http://kangax.github.io/compat-table/es6/#node65 . Can you provide errors and logs with `"debug": true` preset-env option?

**Comment by Spy-Seth** [comment]
I could easily reproduce the error through my BDD test. The full output will have some unesseray log noise so I put it in a gist. I will put here only part that seems important for this issue.

Here the debug info of this preset:
```
babel-preset-env: `DEBUG` option

Using targets:
{
  "node": 6.9
}

Modules transform: commonjs

Using plugins:
  transform-exponentiation-operator {}
  transform-async-to-generator {}
  syntax-trailing-function-commas {}

Using polyfills:
  es6.weak-map {}
  es6.weak-set {}
  es6.reflect.apply {}
  es6.reflect.construct {}
  es6.reflect.define-property {}
  es6.reflect.delete-property {}
  es6.reflect.get {}
  es6.reflect.get-own-property-descriptor {}
  es6.reflect.get-prototype-of {}
  es6.reflect.has {}
  es6.reflect.is-extensible {}
  es6.reflect.own-keys {}
  es6.reflect.prevent-extensions {}
  es6.reflect.set {}
  es6.reflect.set-prototype-of {}
  es6.symbol {}
  es6.regexp.flags {}
  es7.array.includes.js {}
  es7.object.values {"node":7}
  es7.object.entries {"node":7}
  es7.object.get-own-property-descriptors {"node":7}
  es7.string.pad-start {}
  es7.string.pad-end {}
  web.timers {}
  web.immediate {}
  web.dom.iterable {}
```



The main error is (the others are side effect):

```
    TypeError: Class constructor HttpClient cannot be invoked without 'new'
         at Object.createInstance (/home/node/node_modules/skippy/src/ObjectHelper.js:25:17)
         at ServiceDefinition.createInstance (/home/node/node_modules/skippy/src/ServiceDefinition.js:47:25)
         at Container.getService (/home/node/node_modules/skippy/src/Container.js:64:45)
         at Container.getService (/home/node/app/src/Bootstrap/Container.js:32:28)
         at /home/node/app/src/Testing/IntegrationTestWorld.js:50:79
         at undefined.next (native)
         at step (/home/node/app/src/Testing/IntegrationTestWorld.js:37:191)
         at /home/node/app/src/Testing/IntegrationTestWorld.js:37:437
         at /home/node/app/src/Testing/IntegrationTestWorld.js:37:99
at IntegrationTestWorld.reset (/home/node/app/src/Testing/IntegrationTestWorld.js:66:11)
```


I've isolate the issue in a reproducible code:

```javascript
function createInstance(constructor, newInstanceArguments) {
    // From: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#Using_apply_to_chain_constructors
    var proxyConstructor = Object.create(constructor.prototype);

    constructor.apply(proxyConstructor, newInstanceArguments); // This fail without the es 2015 class transformer

    return proxyConstructor;
};

class Foo { }

const foo = createInstance(Foo); // Fail

console.log(foo);
```

To instantiate my service I use a dependency container, so I do not do myself the `new`. In the container (that is also written by me) [I use the `createInstance` function to instantiate a class reference)[https://github.com/rezzza/skippy/blob/ce32dfab47a8b5997bb37ea5f0217866e5edfc3c/src/ObjectHelper.js#L21-L28
].

So without the `transform-es2015-classes` transformer it fail. I'm surprise by this incompatible behavior.

Full logs: https://gist.github.com/Spy-Seth/dc8d26febbfdd09164e01871d602374c

**Comment by hzoo** [comment]
@Spy-Seth `Class constructor Foo cannot be invoked without 'new'` is from node itself because it's using native classes. It's not a bug with env but part of the spec (try the snippet in the node repl or chrome)

Basically a bug with the classes transform / non-spec compilant behavior

**Comment by Spy-Seth** [comment]
Ok I rely on an edge case of the `transform-es2015-classes` with my instantiate method. I've fix this.

But I still do not understand why I need to activate the presets `transform-es2015-destructuring` and `transform-regenerator`. Without them seems that my async function stop working correctly:

```
TypeError: Generator is already running
    at undefined.next (native)
    at step (/home/node/app/src/WebsiteBuilding/Infra/HttpEventStore.js:41:191)
    at /home/node/app/src/WebsiteBuilding/Infra/HttpEventStore.js:41:361
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Spy-Seth** [comment]
So after some digging it's maybe a node bug: https://github.com/nodejs/node/issues/6625
