### ISSUE TITLE
How to combine with another preset like "react"?

### ISSUE THREAD

**Issue by tmitchel2** [babel/babel-preset-env#123]
Im trying to use this preset with the "react" preset also, I've tried many combinations but i can't get it to work.  Whats the expected way of combining "env" and "react" presets?

**Comment by yavorsky** [comment]
@tmitchel2 Hi! Just add react preset as well as env:

```
{
  presets: [
    "react",
    [ "env", {
      "targets": {
        browsers: '> 2%'
      }
    }]
  ]
}
```

**Comment by tmitchel2** [comment]
Now i feel stupid, thanks!  I must have been putting react inside the env array 👍
