### ISSUE TITLE
Is the version published to NPM from master?

### ISSUE THREAD

**Issue by skattyadz** [babel/babel-preset-env#126]
This is a strange question, but I'm getting errors like

```
Module build failed: Error: Invalid plugins/built-ins 'es6.typed.data-view,es6.typed.int8-array,es6.typed.uint8-array,es6.typed.uint8-clamped-array,web.timers,web.immediate,web.dom.iterable' passed to 'exclude' option.
```

Looking at version `1.1.6` in my `node_modules` folder, https://github.com/babel/babel-preset-env/commit/84d10f31fedc06b7c3d73135dbda50117c61059f hasn't been applied. Also, `validIncludesAndExcludes` is limiting `builtIns` to 4 items:

```
var validIncludesAndExcludes = exports.validIncludesAndExcludes = [].concat(Object.keys(_pluginFeatures2.default), Object.keys(MODULE_TRANSFORMATIONS).map(function (m) {
  return MODULE_TRANSFORMATIONS[m];
}), Object.keys(_builtIns2.default).slice(4));
```

It looks to me like a WIP was incorrectly published to NPM. Could that be the case?

Thanks

**Comment by hzoo** [comment]
Hm that's really weird, that's possible will check it.

**Comment by hzoo** [comment]
ok not sure how that happened.. will look to prevent that in the future too. Thanks for the catch

**Comment by hzoo** [comment]
published 1.1.7 https://unpkg.com/babel-preset-env@1.1.7/lib/index.js should have the changes now.

**Comment by skattyadz** [comment]
Awesome, thanks

**Comment by hzoo** [comment]
Oh yeah and report back if your issues are fixed!

**Comment by skattyadz** [comment]
I can confirm that everything is A-OK now!
