### ISSUE TITLE
modules/es7.array.includes.js -> modules/es7.array.includes

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#129]
In our config file it's unncessary to use `.js` since it ends up being a require/import statement.

`require("es7.array.includes.js")` -> `require("es7.array.includes")`

```js
  "es6.math.trunc": {
    "chrome": 38,
    "edge": 12,
    "firefox": 25,
    "safari": 7,
    "node": 0.12,
    "ios": 10,
    "opera": 25
  },
  "es7.array.includes.js": { // remove .js here
    "chrome": 47,
    "edge": 14,
    "firefox": 43,
    "safari": 10,
    "ios": 10,
    "opera": 34
  },
```

The `.js` is unnecessary and inconsistent (not sure why this happened other than a typo)

- [x] comment below if you are working on this!
- [x] EDIT: need to change https://github.com/babel/babel-preset-env/blob/master/data/built-in-features.js#L123
- [x] Basically just have to change the file https://github.com/babel/babel-preset-env/blob/00feed3ed3b684f4aff06b4182e9a0307c447621/data/built-ins.json#L661 + fix failing tests.
- [x] You can run tests with `npm run test`

**Comment by roman-yakobnyuk** [comment]
Let me try fix it up! =) Never commited anything before but this looks easy.

**Comment by roman-yakobnyuk** [comment]
Here, is this okay? Any feedback welcome, my first PR for open source =) 
https://github.com/babel/babel-preset-env/pull/131

**Comment by hzoo** [comment]
Yep will check it out 😄

**Comment by guillaumevincent** [comment]
:heart: this beginner-friendly tag :)

**Comment by hzoo** [comment]
@guillaumevincent Yeah planning for all our repos to have it plus update our docs to render recent ones https://github.com/babel/babel.github.io/pull/1126

**Comment by hzoo** [comment]
Done by @roman-yakobnyuk in https://github.com/babel/babel-preset-env/pull/131 👍
