### ISSUE TITLE
Easier way to exclude/include (especially builtIns)

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#132]
Context:

Docs for the include/exclude options: https://github.com/babel/babel-preset-env#include
Example: https://github.com/babel/babel-preset-env#example-with-includeexclude

---

This is a bit more involved, but still basically the gist is changing indexOf to handle regex.

This is mostly for built-ins.

There's a lot of them: https://github.com/babel/babel-preset-env/blob/master/test/fixtures/preset-options/use-builtins-all/expected.js

If we don't use `reflect` or `number` or `math` you currently have to list each one individually since we do an `indexOf` check

I think we can change it to accept a regex or glob (I think regex) to match multiple of them.

So instead of:

```json
{
  "exclude": [
    "es6.math.acosh",
    "es6.math.asinh",
    "es6.math.atanh",
    "es6.math.cbrt",
    "es6.math.clz32",
    "es6.math.cosh",
    "...etc"
  ]
}
```

be able to handle something like

```json
{
  "exclude: [/^es6.math.+/]
}
```

The current logic is https://github.com/babel/babel-preset-env/blob/8eb0c0799cefe3548216a3b2bc372e21dcd3b065/src/index.js#L250-L257
and https://github.com/babel/babel-preset-env/blob/8eb0c0799cefe3548216a3b2bc372e21dcd3b065/src/index.js#L277-L279

```js
    polyfills = Object.keys(builtInsList)
      .filter((builtInName) => isPluginRequired(targets, builtInsList[builtInName]))
      .concat(defaultInclude)
      .filter((plugin) => exclude.builtIns.indexOf(plugin) === -1) // here
      .concat(include.builtIns); // here
```

```js
  const allTransformations = transformations
  .filter((plugin) => exclude.plugins.indexOf(plugin) === -1) // here
  .concat(include.plugins); // here
```

- [ ] change indexOf check to handle regex
- [ ] tests

**Comment by hawkrives** [comment]
Can we use Array#find? Probably not. I can take a stab at this in a minute!

**Comment by bicycleChen** [comment]
I think we should check if it is `regex` pattern or pure Array list?

**Comment by bicycleChen** [comment]
Another question, is it possible to configure like this below?

```
  {
    "include": ["/^es6.math.+/", "es6.reflect.apply"]
  }
```

**Comment by yavorsky** [comment]
@bicycleChen It's possible if we would wrap value: `new RegExp("^es6.math.+")`, but why? Using strings means use strict matching: `plugin === exclusion` and using RegExp could be determined `exclusion instanceof RegExp` and then used as `exclusion.match(plugin)`.

**Comment by brokenmass** [comment]
i think @bicycleChen suggestion is correct as the module configuration might be defined in the package.json file where you cannot use regexes.

could a wildcards approach be a simpler solution ?
 ```
{
  "include": ["es6.math.*", "es6.reflect.apply"]
}
```

**Comment by yavorsky** [comment]
@brokenmass Really, `package.json` 👍 

So, if we are going to deviate RegExp spec, we could just specify: 
```
{
  "exclude": [
      "es6.typed.data-view", // specific builtIn
      "es6.math",  // whole module
      "es7" // whole ES edition
  ]
}
```

**Comment by brokenmass** [comment]
I suggested the wildcard as it's more explicit and avoid aliasing issues.
for example `"exclude": ["es6.reflect.get"]` would become ambiguous if you just do a substring check (`es6.reflect.get, es6.reflect.get-own-property-descriptor, es6.reflect.get-prototype-of`)

It could also allow something like 
```
"exclude": [
  "*.object.*" // Don't touch my objects :D
]
```

**Comment by yavorsky** [comment]
All built-ins have format like: **es.module.feature**, so specifying `get` means specify `get` feature, because of `get-prototype-of` and `get-own-property-descriptor` is definitely different things. It's something like comparing `es6.array.fill` and `es6.array.find` by indicating `es6.array.fi`.
5 more messages there and we will write own css-in-json. :D
```
"exclude": [
  "*:not(es6).object.*:first-of-type" // css-in.json v.0.0.1-alpha
]
```

**Comment by hzoo** [comment]
Yeah I would like the simplest thing for both us and users

**Comment by hawkrives** [comment]
From using other software, I've come to have one of three expectations, personally: either it accepts only exact matches (current behavior), it does shell-like globbing (`*.object.*`), or it accepts regexes, usually denoted by leading/trailing `/` (`/es(6|7)\.math\..*/`).

I'm willing to try and implement globs, regexes, or whatever else the thread decides on.

Cheers! 😄

**Comment by bicycleChen** [comment]
Got a question 🙋
I am wondering whether this transition will affect `checkDuplicateIncludeExcludes` or not?

**Comment by hzoo** [comment]
very good point.. I guess it will have to

**Comment by bicycleChen** [comment]
Got an another question 🙋
I think there gonna be several places below that should be modified in this pr.

* validatePluginsOption (include builtins)
* validIncludesAndExcludes (include builtins)
* checkDuplicateIncludeExcludes (include builtins)
* buildPreset 
  *  useBulitIns polyfills
  *  allTransformations

But I am not sure about that, probably I have skipped some place that is crucial.

**Comment by mattijs** [comment]
It would be great if plugins and polyfills could be included/excluded separately. Currently setting `useBuiltIns` to `true` will include relevant plugins and polyfills.

It would be great if these could be enabled/disabled using another flag, something along the lines of `includePlugins` and `generatePolyfills`. The `useBuiltIns` option would default these two to `true` if not provided.

**Comment by restrry** [comment]
how should work `include` and `exclude` options in case of intersection? example:
```
    "include": ["es6.typed"],
    "exclude": ["es6.typed.data-view"]
```
the rule with higher specificity should win?
