### ISSUE TITLE
how to use browserslist option in package.json

### ISSUE THREAD

**Issue by pavel06081991** [babel/babel-preset-env#137]
I've read that it is possible to use browserslist key in package.json for both babel and postCSS to use this list of browsers, but babel env preset seems does not understand it. Here is my package.json

```
  "babel": {
    "presets": [
      [
        "env", {
          "modules": false,
          "useBuiltIns": true
        }
      ],
      "react"
    ]
  },
  "browserslist": [
    "last 1 Chrome versions"
  ]
```
Am I right that there is no support for browserslist key or maybe I do something wrong?

**Comment by yavorsky** [comment]
@pavel06081991 Hi! It's not implemented yet, but we are going to add this in the near future. 
For more info look into https://github.com/babel/babel-preset-env/issues/108.

**Comment by pavel06081991** [comment]
@yavorsky thank you
