### ISSUE TITLE
README: Explain how you can use google analytics -> browserslist to generate your targets

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#140]
Reference: https://twitter.com/addyosmani/status/820467784995913728

Should be able to compile less by checking the browser usage from analytics!

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"] // refine these
      }
    }]
  ]
}
```

Unless we should just start making a new doc for examples?

**Comment by addyosmani** [comment]
I think a new doc or guide would be helpful here so 👍 

Based on our last chat we were thinking about strategies for serving down a different bundle to modern browsers and another to older browsers. It might help folks feel a little safer with this if it was entirely based on data from their analytics.

**Comment by yavorsky** [comment]
Custom Usage Data steps are too complicated. I think we are able to automate this by making a small script to parse google analytics data into browserslist's format bypassing caniuse.

**Comment by hzoo** [comment]
K i'l close for now
