### ISSUE TITLE
replace manual electron-to-chromium file with external package

### ISSUE THREAD

**Issue by Kilian** [babel/babel-preset-env#142]
I just created an electron-to-chromium package that provides the same object that you manually keep in https://github.com/babel/babel-preset-env/blob/master/data/electron-to-chromium.js but then automatically generated as suggested by @kevinsawicki here: https://github.com/babel/babel-preset-env/pull/55#discussion_r91378631

Would you consider replacing the file with `require('electron-to-chromium').versions`?

The package is here: https://www.npmjs.com/package/electron-to-chromium
The git repository is here: https://github.com/Kilian/electron-to-chromium

It was created after discussion in the browserlist repository: https://github.com/ai/browserslist/issues/96 Where the main goal for me was to make sure Browserlist understood "Electron >= 1.4", but @ai (rightfully) wanted to keep it out browserlist until it proved popular enough. Given that you already use a mapping file, switching to electron-to-chromium makes more sense for you.

**Comment by hzoo** [comment]
Yep for sure, can make the PR if you'd like as well (I didn't want to make a mapping myself so I asked so this is great)

**Comment by Kilian** [comment]
Will do :)

**Comment by Kilian** [comment]
I'm working on replacing the file with my package, but one of the tests are failing. However, the test in question says that electron 1.0 uses chrome 50. My package and the actual list says it uses chrome 49: https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/index.json so i'll be sure to update the tests too :)

**Comment by Kilian** [comment]
Additionally, other tests assumed electron 1.5 === chrome 54, but that's also not a given (yet). I've updated both, PR incoming!
