### ISSUE TITLE
[bug]? still use plugin < target version

### ISSUE THREAD

**Issue by bluelovers** [babel/babel-preset-env#143]
`babel-preset-env: `DEBUG` option`

```
Using targets:
{
  "firefox": 52,
  "node": 7.4 
}

Modules transform: commonjs

Using plugins:
  transform-es2015-destructuring {"node":6.5} // node is 7.4 , but still use 6.5 plugin
  transform-es2015-for-of {"node":6.5}
  transform-es2015-function-name {"node":6.5}
  transform-es2015-literals {"node":4}
  transform-exponentiation-operator {"firefox":52}
  syntax-trailing-function-commas {"firefox":52}
```

```
{
  "presets": [
    [
      "env",
      {
        "debug": true,
        "exclude": [
          "transform-async-to-generator",
          "transform-regenerator", "transform-es2015-parameters"
        ],
        "targets": {
          "firefox": 52,
          "node": 7.4
        }
      }
    ]
  ]
}
```

**Comment by yavorsky** [comment]
Hi @bluelovers. It was included because you specified firefox 52. 
But yes logs must show `firefox: 52` instead of node's version and `node: 7.4` for *exponentiation-operator* and *trailing-function-commas*. 

https://github.com/babel/babel-preset-env/blob/master/src/index.js#L222-L226 takes keys from data/plugins.json items, but should from `targets` and filter it for a lower version or exclusion in plugin's object.

Thanks!

**Comment by beardedtim** [comment]
Before I dig into this, are we wanting it to where it does not use plugins for versions of node < what was given? So in the above example, it would not use the following because they are below the node version:

```
transform-es2015-destructuring {"node":6.5} 
transform-es2015-for-of {"node":6.5}
transform-es2015-function-name {"node":6.5}  
transform-es2015-literals {"node":4}
```

or am I totally misunderstanding this issue?

**Comment by existentialism** [comment]
Hey @beardedtim! The bug is actually that the debug output that shows which platform/target that causes the plugin to be included is incorrect, the above should be:

```sh
Using plugins:
  transform-es2015-destructuring {"firefox":52}
  transform-es2015-for-of {"firefox":52}
  transform-es2015-function-name {"firefox":52}
  transform-es2015-literals {"firefox":52}
  transform-exponentiation-operator {"node":7.4}
  syntax-trailing-function-commas {"node":7.4}
```
