### ISSUE TITLE
Debug output omitted with 2 .babelrc files

### ISSUE THREAD

**Issue by noinkling** [babel/babel-preset-env#147]
I have a Node web app where both the server and frontend use Babel. The frontend is served using `webpack-dev-middleware` in development, so I can just launch the app in one command with `babel-node`.

Root level `.babelrc` for server:
```
{
  "presets": [
    ["env", {
      "debug": true,
      "targets": {
        "node": "current"
      }
    }]
  ]
}
```

Subdirectory `.babelrc` for frontend:
```
{
  "presets": [
    ["env", {
      "debug": true,
      "modules": false
      // no "targets" for now, just defaulting to "latest" preset
    }],
    "react"
  ],
  "env": {
    "development": {
      "plugins": ["react-hot-loader/babel"]
    }
  }
}
```

When the `debug` option is set to `true` in both files, only the output for the server (Node) one is shown - I would expect both to be shown. If I remove that option from the Node `.babelrc`, the frontend debug output then shows up fine with all the stuff from `babel-preset-latest` as I expect.

It's important to note that the bug doesn't affect actual functionality and the setup works great otherwise.

Edit: I expect it has something to do with the [`hasBeenLogged` flag variable](https://github.com/babel/babel-preset-env/blob/55aa7ff3531ec94eed780dd90072543af3614567/src/index.js#L180).

**Comment by frenzzy** [comment]
Also debug output omitted with `cacheDirectory: true` option in [babel-loader](https://github.com/babel/babel-loader#options)
