### ISSUE TITLE
You gave us a visitor for the node type "ForAwaitStatement for OSX/Node4

### ISSUE THREAD

**Issue by sheerun** [babel/babel-preset-env#148]
It happens with babel-preset-env 1.1.8, only on OSX, and only on Node 4.

I'm bumping this issue out of #39 

Here's example build that shows the issue:
https://travis-ci.org/sheerun/modern-node/jobs/193698844

Here's sample repository that shows the issue:
https://github.com/sheerun/modern-node

**Comment by hzoo** [comment]
Closing this issue as it's been inactive

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
