### ISSUE TITLE
Verify IE, other environments

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#15]
Currently: ["chrome, edge, firefox, safari, node"](https://github.com/babel/babel-preset-env/blob/b80dfaaa7f88cd569b037bd54fc1712329af13d1/data/plugins.json#L3-L7)

https://kangax.github.io/compat-table/es6/ supports a lot more?
- [x] First which environments? (ie, ios, android)
- [ ] How do we fix data/logic around edgecases/make it robust?
  - https://github.com/babel/babel-preset-env/blob/b80dfaaa7f88cd569b037bd54fc1712329af13d1/scripts/build-data.js#L34-L45 is kind of a hack
  - as is https://github.com/babel/babel-preset-env/blob/b80dfaaa7f88cd569b037bd54fc1712329af13d1/scripts/build-data.js#L65-L72

**Comment by jdalton** [comment]
If anything IE 11 would be it. Going forward it'll be the last IE supported by MS.

**Comment by hzoo** [comment]
If we want to replace es2015+es3 transforms we should make it work for ie < 11 too right?

**Comment by jdalton** [comment]
In terms of work, I'd prioritize supported versions before unsupported versions is all.

**Comment by hzoo** [comment]
Oh ok - it's actually not hard just tedious to make sure the data is correct

**Comment by stevewillard** [comment]
I would like to use this preset, but I need IE11 support first. ios_saf would be great, too.

**Comment by hzoo** [comment]
you can run the preset with debug option and see if it works? it should already work since unknown values will run all transforms

**Comment by stevewillard** [comment]
I can't quite tell if it's working (I don't have access to IE at the moment).

Here is my preset config:
```
"presets": [
    ["env", {
      "targets": {
        "node": 6.5,
        "browsers": [
          "chrome >= 52",
          "firefox >= 47",
          "ie >= 11",
          "edge >= 13",
          "safari >= 9"
        ]
      },
      "loose": true,
      "modules": false,
      "debug": true
    }],
    "react",
    "stage-0"
  ]
```

And debug produces a lot of output. Here's a snippit:
```
Using targets: {
  "chrome": 52,
  "edge": 13,
  "firefox": 47,
  "ie": 11,
  "safari": 9,
  "node": 6.5
}

Using plugins:

module: false
transform-es2015-arrow-functions {
  "chrome": 47,
  "edge": 13,
  "firefox": 45,
  "safari": 10,
  "node": 6
}
transform-es2015-block-scoped-functions {
  "chrome": 41,
  "firefox": 46,
  "ie": 11,
  "safari": 10,
  "node": 4
}
transform-es2015-block-scoping {
  "chrome": 49,
  "firefox": 51,
  "safari": 10,
  "node": 6
}
...
```

I'll see if I can get my local VM working so I can try out IE.

**Comment by hzoo** [comment]
Yeah it prints out all the plugins it's using. It should be all of them

**Comment by hzoo** [comment]
Forgot I already "added" support but we need to verify everything

**Comment by tleunen** [comment]
> it's actually not too hard just tedious to make sure the data is correct

Can this be automated?

**Comment by hzoo** [comment]
Ok my original description is vague and the issues I was concerned about make sense - the map in https://github.com/babel/babel-preset-env/blob/b80dfaaa7f88cd569b037bd54fc1712329af13d1/scripts/build-data.js#L34-L45 works fine
