### ISSUE TITLE
target node 4/4.3 transpiles everything to es5

### ISSUE THREAD

**Issue by binoculars** [babel/babel-preset-env#150]
### Setting
```js
[ 'env', { targets: {node: 4.3} } ]
```

### Debug output
```
babel-preset-env: `DEBUG` option

Using targets:
{
  "node": 4.3
}

Modules transform: commonjs

Using plugins:
  transform-es2015-arrow-functions {"node":6}
  transform-es2015-block-scoping {"node":6}
  transform-es2015-classes {"node":5}
  check-es2015-constants {"node":6}
  transform-es2015-destructuring {"node":6.5}
  transform-es2015-for-of {"node":6.5}
  transform-es2015-function-name {"node":6.5}
  transform-es2015-object-super {"node":5}
  transform-es2015-parameters {"node":6}
  transform-es2015-spread {"node":5}
  transform-es2015-sticky-regex {"node":6}
  transform-es2015-unicode-regex {"node":6}
  transform-regenerator {"node":6}
  transform-exponentiation-operator {}
  transform-async-to-generator {}
  syntax-trailing-function-commas {}

```

## Works as expected:
```js
[ 'env', { targets: {node: 6} } ]
```

## [Node v4.0.0 Release Notes](https://nodejs.org/en/blog/release/v4.0.0/)
> Node.js v4.0.0 contains V8 v4.5, the same version of V8 shipping with the Chrome web browser today. This brings with it many bonuses for Node.js users, most notably a raft of new ES6 features that are enabled by default including block scoping, classes, typed arrays (Node's Buffer is now backed by Uint8Array), generators, Promises, Symbols, template strings, collections (Map, Set, etc.) and, new to V8 v4.5, arrow functions.

Shouldn't [this line](/babel/babel-preset-env/blob/master/data/plugins.json#L7) have 3 instead of 6?

**Comment by yavorsky** [comment]
@binoculars Node.js 4 supports only 52% of available es6 features. And preset-env includes only features that covered fully. For ex, you can declare arrow function, but in 4-th node.js it has incorrect precedence. Or `const`, but it has only basic support (no block scoped, cannot be in statements, etc). So, to use the feature completely we must add the whole plugin. 

[Look](https://kangax.github.io/compat-table/es6/#node4), preset-env ignore only features that have 100% support (dark-green).

**Comment by binoculars** [comment]
I was looking for a replacement to jbach/babel-preset-es2015-node4 which was deprecated in favor of this preset, but the behavior is different. I suppose I can exclude the other presets manually.

**Comment by yavorsky** [comment]
@binoculars Yes, it's not a problem: https://github.com/babel/babel-preset-env#exclude
But be careful to ignore plugins in favor of not fully implemented features in node 4.

**Comment by SimenB** [comment]
I ended up doing this, which gave me no difference in compiled code vs `es2015-node4`

```js
["env", {
  "targets": {
    "node": 4
  },
  "exclude": [
    // These are not _really_ needed for node@4
    "transform-es2015-classes",
    "transform-es2015-block-scoping",
    "transform-es2015-arrow-functions"
  ]
}]
```
