### ISSUE TITLE
Node target version

### ISSUE THREAD

**Issue by anilanar** [babel/babel-preset-env#153]
I have the following `.babelrc`:

```
{
  "presets": [
    ["env", {
      "targets": {
        "node": 4.7
      }
    }]
  ]
}
```

With this setup, arrow functions are converted to normal functions.

If I use `"node": 4`, still the same.

If I use `"node": 6`, then it stops converting arrow functions.

**Comment by hawkrives** [comment]
You can see the full discussion in https://github.com/babel/babel-preset-env/issues/150, but in short, Node 4 had bugs with a lot of es6 constructs, so preset-env transpiles them down to es5.

Node 6 fixed many of those bugs, so preset-env doesn't transpile them to es5.

> Note: I have no idea what I'm talking about.

**Comment by anilanar** [comment]
That makes sense. I was confused by this part in the README:

> For example, if you are building on Node 4, arrow functions won't be converted, but they will if you build on Node 0.12.

**Comment by hzoo** [comment]
This is a general question I don't know the answer to: it's possible a environment/browser/node supports the simplest case or most cases but when do we decide to compile or not? Right now we are just being conservative.

**Comment by anilanar** [comment]
I guess it is fine to convert based on worst case scenario instead of doing additional parsing/analysis to be less "conservative". This is a simple preset with a simple premise. Additional complexity should not be welcome, IMO.

**Comment by hzoo** [comment]
Yeah there's already too much config haha. And the idea is that whenever the new browser supports it, it will be updated so either you need to but in the work to exclude/include yourself or we need to support this "loose" mode feature which is probably a bad idea
