### ISSUE TITLE
Missing built-ins environment data

### ISSUE THREAD

**Issue by spencerhakim** [babel/babel-preset-env#154]
While inspecting the compiled output for `import "core-js"` in my project, I noticed several polyfills were being included that definitely didn't need to be. It seems several entries in `built-ins.json` are missing `"node"` fields.

For example, `Array.prototype.includes` is [defined in Node 6.0+](http://kangax.github.io/compat-table/es2016plus/#node6), but is imported anyway since [no minimum Node version is defined](https://github.com/babel/babel-preset-env/blob/master/data/built-ins.json#L669).

I haven't checked if any other environments are missing data, but `es6.symbol`, `es6.reflect.*`, and a few others are also missing `"node"` fields.

**Comment by existentialism** [comment]
@spencerhakim thanks for the report!

Definitely looks like an issue with not handling [`equals: chrome50`](https://github.com/kangax/compat-table/blob/gh-pages/environments.json#L1421) properly when we parse compat-table data.

**Comment by existentialism** [comment]
Fixed in https://github.com/babel/babel-preset-env/pull/180
