### ISSUE TITLE
Select browsers based on particular feature support 

### ISSUE THREAD

**Issue by graingert** [babel/babel-preset-env#157]
Eg all browsers that support async await,  would select Chrome or all browsers that support arrow functions, would select most modern browsers

**Comment by yavorsky** [comment]
@graingert it's not safe to ignore transpiling for targets that don't support features fully.
For example, let's look at [constants](https://kangax.github.io/compat-table/es6/#test-const). Minimum targets for this feature looks like:
```json
"chrome": 49
"firefox": 51
"safari": 10
"node": 6
"ios": 10
"opera": 36
```
These targets support all 16/16 const's features, like *it's block-scoped*, *for-in loop iteration scope*, *for-of loop iteration scope* etc. 
For example *for-in loop iteration scope* isn't supported in IE 11, node 4, FF 45. 
So something like: 
```js
for (const key in {a: 1}) {
  console.log(key);
}
```
won't work on these targets, but preset's purpose is to avoid such things. 
Including plugins even if 1 of 40 features isn't supported gives us guarantee to use preset with maximum safety with specified targets. You always free to [exclude](https://github.com/babel/babel-preset-env#exclude) some plugins at your own risk or specify targets that cover some features fully.

Also "particular feature support" is too blurry. Is 1/16 coverage is particular support? Node.js 0.12 has basic constants support, but it even won't cause an error after constant redefining.

**Comment by graingert** [comment]
@yavorsky I don't see that being a problem.  If I wanted to target all browsers supporting const I'd expect babel to determine a set of browsers to target that supported 16/16 const

**Comment by hzoo** [comment]
I don't really get why you'd need to only target browsers that support a feature? The point of this preset is to automatically compile if native support is there for the browsers you support. The input is the targets themselves while in this case it seems like you want the syntax to be the input?
