### ISSUE TITLE
Add PhantomJS as a target

### ISSUE THREAD

**Issue by graingert** [babel/babel-preset-env#158]
Now that Phantom 2.5 supports ES2015 it would be good to add it as an Alias to chrome:

depends on https://github.com/kangax/compat-table/issues/1013

**Comment by graingert** [comment]
would be handy to support `phatomjs: current` babelrc JSON as well as `phantomjs: require('phantomjs-prebuilt/package.json').version`

**Comment by chicoxyzzy** [comment]
Should we can close this issue? PhantomJS is not maintained anymore

**Comment by hzoo** [comment]
sure, can use uglify/forcetransforms option as well

**Comment by graingert** [comment]
@hzoo uglify?
