### ISSUE TITLE
Add greenkeeper bot to keep build-data green.

### ISSUE THREAD

**Issue by yavorsky** [babel/babel-preset-env#159]
I think we need to add automatic updates for our dependencies, especially would be useful for [compat-table](https://github.com/kangax/compat-table).
Seems like [Greenkeeper](https://github.com/integration/greenkeeper) could help us.

**Comment by xtuc** [comment]
Yes that would be great.

/cc @kangax

**Comment by hzoo** [comment]
I don't think it's a big deal unless we want to make a new release anytime compat-table updates (doesn't need to be that often - I can just whitelist compat-table only I suppose)
