### ISSUE TITLE
Cannot find module 'core-js/modules/es6.map'

### ISSUE THREAD

**Issue by GitScrum** [babel/babel-preset-env#162]
https://travis-ci.org/GitScrum/posthtml-beautify/jobs/199149037

**Comment by hzoo** [comment]
This is probably due to npm 2.

You can solve this with with npm 3 or making core-js a dependency

**Comment by GitScrum** [comment]
> This is probably due to npm 2.  

Most likely

> You can solve this with with npm 3 or making core-js a dependency

I would not want to make additional settings, or to have according to core-js

If it is not solved you can close issue. Thanks !
