### ISSUE TITLE
Incorrect browser targets

### ISSUE THREAD

**Issue by tleunen** [babel/babel-preset-env#163]
Hey,

I have these targets:
```
"targets": {
  "browsers": [
    "last 2 Chrome versions",
    "last 2 Firefox versions",
    "last 2 Edge versions",
    "last 2 Opera versions",
    "last 2 Safari versions",
    "ie 11"
  ],
  "node": "current"
},
```
And with the debug option, the preset gives me this:
```
{
  "chrome": 57,
  "edge": 14,
  "firefox": 53,
  "ie": 11,
  "safari": 10,
  "node": 7.5
}
```
So Chrome 57 isn't really "last 2 versions". Since the last stable version of Chrome is still 56.

When using the same settings, with the same `getLowestVersion` from your package, I'm getting this from browserslist itself:
```
chrome: 55
edge: 13
firefox: 50
ie: 11
safari: 9
```

Why is `babel-preset-env` provide different values?

**Comment by yavorsky** [comment]
@tleunen Hi!
Just tried with the same targets and got:
```
{
  "chrome": 55,
  "edge": 13,
  "firefox": 50,
  "ie": 11,
  "safari": 9,
  "node": 7.5
}
```
Are you using 1.1.8 preset's version?

**Comment by tleunen** [comment]
Hmm that's weird. I just tested again and now I get the right values...
Not sure what happened... Maybe it was a cache issue or something...

Thanks!
