### ISSUE TITLE
Async-to-generator plugin is not excluded properly

### ISSUE THREAD

**Issue by Whoaa512** [babel/babel-preset-env#165]
Basically if you add `transform-async-to-generator` to the exclude it is not respected. 

Created a repo with the reproduction of the bug.
https://github.com/Whoaa512/fast-async-babel-env-repro

**Comment by yavorsky** [comment]
@Whoaa512 Hi! You are trying to include 2 presets: preset-env and stage-0. Stage-0 preset includes stage-1, stage-2 and stage-3. Stage-3 includes `transform-async-to-generator` plugin. preset-env doesn't responsible for other presets. Stage presets aren't so flexible as babel-preset-env and, unfortunately, you can exclude `transform-async-to-generator` from stage-3.

So, you can list all plugins you need from stage-0 in `plugins` field or create own preset based on plugins from stages for your needs.

**Comment by Whoaa512** [comment]
Oh, cool thank you :) Didn't realize.
