### ISSUE TITLE
support node 7.6

### ISSUE THREAD

**Issue by graingert** [babel/babel-preset-env#166]
depends on https://github.com/kangax/compat-table/pull/1033

**Comment by yavorsky** [comment]
@graingert Good point! We could add it right after it will be merged.

**Comment by hulkish** [comment]
I just wanted to add.. that I hope this automatically excludes `transform-async-to-generator`. Currently, that is not the case for `babel-preset-env@1.1.10`

**Comment by hulkish** [comment]
@hzoo does this include https://github.com/babel/babel-preset-env/issues/166#issuecomment-282618511?

**Comment by existentialism** [comment]
@hulkish yes: https://github.com/babel/babel-preset-env/pull/177/files#diff-6e7d3984027b6e9cb5041f9f5572e831R179

**Comment by noinkling** [comment]
@hulkish Yes, with debug option turned on:

```
Using plugins:
  transform-exponentiation-operator {"node":7.6}
  syntax-trailing-function-commas {"node":7.6}
```

**Comment by batjko** [comment]
I'm not sure I'm using this correctly.
I have just updated to node 7.7, and am trying to get the native async/await to work.
I still have to use babel for modules, so I am using the `env` preset.

However, I keep getting the regenerator error:

index.js:
```js
require('babel-register')
require('./sandpit')
```

sandpit.js
```js
async function printNorris(category) {
  const norris = await axios.get(`https://api.chucknorris.io/jokes/random?category=${category}`)
  console.log(norris.data.value)
}
printNorris('dev')
```

`node index.js` -> Output:
```bash
  var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
                               ^
ReferenceError: regeneratorRuntime is not defined
    at D:\git\XXX\sandpit.js:4:32
    at Object.<anonymous> (D:\git\XXX\sandpit.js:29:2)
    at Module._compile (module.js:571:32)
    at loader (D:\git\XXX\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\git\XXX\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

I thought this should work just fine now, without babel having to transform the async/await constructs. No?

**Comment by noinkling** [comment]
@batjko Check the examples in the readme, your .babelrc should look something like:

```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      }
    }]
  ]
}
```

**Comment by batjko** [comment]
Ha! It does the trick, @noinkling.
I did read the README, but it wasn't clear to me that this was necessary. I assume there is some incompatibility with the default env preset? 

Thanks for your quick response!

**Comment by hzoo** [comment]
> default env preset

If you don't pass any options it acts the same as preset-latest which compiles everything. You have to tell the preset what you support or it doesn't know what to not compile, make sense?

**Comment by batjko** [comment]
> You have to tell the preset what you support or it doesn't know what to not compile, make sense?

Yup, makes now.
