### ISSUE TITLE
targets 6.1 instead of 6.10

### ISSUE THREAD

**Issue by duvillierA** [babel/babel-preset-env#167]
Hi,

Thanks to the Debug output.

Using Node@6.10.0, it looks like `babel-preset-env@1.1.8` using unecessary plugins:

``` bash
Using targets:
{
  "node": 6.1
}

Modules transform: commonjs

Using plugins:
  transform-es2015-destructuring {"node":6.5}
  transform-es2015-for-of {"node":6.5}
  transform-es2015-function-name {"node":6.5}
  transform-exponentiation-operator {}
  transform-async-to-generator {}
  syntax-trailing-function-commas {}
```

.babelrc
```
"presets": [["env", {
    "targets": {
      "node": "current"
    },
    "debug": true
  }]]
```

Is there an issue?

**Comment by yavorsky** [comment]
@duvillierA Hi! Thanks for the issue. The plugins list are correct. All of these things not supported or partially supported in 6.1.

The problem covers in the **incorrect logging**. It was fixed - https://github.com/babel/babel-preset-env/pull/155 but not published yet.
For now, you can use the version from the master but I think we will publish 1.1.9 today.

**Comment by hzoo** [comment]
@duvillierA sorry will publish a new version now.
