### ISSUE TITLE
Recommending alternatives to Uglify in the README

### ISSUE THREAD

**Issue by verekia** [babel/babel-preset-env#190]
I think it would be helpful to recommend ES6-aware minifiers as an alternative to Uglify. Otherwise all the smart optimizations done by `babel-preset-env` are lost, since at the end of the day, we do have to minify production code.

Seems like Babili is the only option?

In the case of Webpack, would you recommend https://www.npmjs.com/package/babili-webpack-plugin for instance?

**Comment by hzoo** [comment]
Yep, babel-preset-env means we would recommend using Babili and that it's vital to this workflow

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel-preset-env/pull/188
