### ISSUE TITLE
%TypedArray%.prototype.every missing in IE11

### ISSUE THREAD

**Issue by alippai** [babel/babel-preset-env#196]
The env preset doesn't include the %TypedArray%.prototype.every polyfill for IE11 target.
IE11 has TypedArray support, however it's missing some functions on the TypedArray instances.

**Comment by yavorsky** [comment]
Hi, @alippai. According to [%TypedArray%.prototype.every in compat-table](https://kangax.github.io/compat-table/es6/#test-typed_arrays_%TypedArray%.prototype.every), IE 11 doesn't support this feature.
Just tried in IE 11.321 and compat-table is actually right:
<img width="436" alt="screen shot 2017-03-08 at 15 23 49" src="https://cloud.githubusercontent.com/assets/1521229/23705660/96c8bad6-0413-11e7-97ac-75f5c1f4ed07.png">

**Comment by alippai** [comment]
As a workaround (until the proper fix) adding the missing imports manually solves the problem:
```import "core-js/modules/es6.typed.data-view";
import "core-js/modules/es6.typed.int8-array";
import "core-js/modules/es6.typed.uint8-array";
import "core-js/modules/es6.typed.uint8-clamped-array";
import "core-js/modules/es6.typed.int16-array";
import "core-js/modules/es6.typed.uint16-array";
import "core-js/modules/es6.typed.int32-array";
import "core-js/modules/es6.typed.uint32-array";
import "core-js/modules/es6.typed.float32-array";
import "core-js/modules/es6.typed.float64-array";```

**Comment by yavorsky** [comment]
@alippai yes, but it isn't what we actually want. I fixed it and need to add a few tests. Going to push today.

**Comment by existentialism** [comment]
Released in https://github.com/babel/babel-preset-env/releases/tag/v1.2.2!
