### ISSUE TITLE
Array.find not being polyfilled

### ISSUE THREAD

**Issue by JasonEtco** [babel/babel-preset-env#210]
Hello!

Array.find isn't being polyfilled as part of my `babel-preset-env` config. Here's the code I'm working with:

```es6
use: {
  loader: 'babel-loader',
  options: {
    presets: [
      ['env', {
        targets: { browsers },
        include: ['es6.array.find'],
        debug: false,
        loose: true,
        modules: false,
        useBuiltIns: true,
      }],
      'react',
      'react-hmre',
    ],
    plugins: [
      [
        'transform-object-rest-spread',
        { useBuiltIns: true },
      ],
      'transform-runtime',
      'transform-class-properties',
    ],
  },
},
```

`browsers` is:
```es6
const browsers = [
  'last 2 versions',
  'ios_saf >= 8',
  'ie >= 10',
  'chrome >= 49',
  'firefox >= 49',
  '> 1%',
];
```

I've tried it both with and without the `include` array, but no luck. Adding `babel-polyfill` to my workflow made it work, so I can do that if necessary but this seems like a bug to me.

Thanks!

**Comment by zloirock** [comment]
`Array.prototype.find` or `Array.find`?

**Comment by JasonEtco** [comment]
@zloirock I'm not sure what the difference is; I'm calling `.find` on an array, like `[1, 2, 3].find(v => v === 1)`

**Comment by JasonEtco** [comment]
In IE10 I'm seeing `Object doesn't support property or method 'find'` in console.

**Comment by zloirock** [comment]
> Adding babel-polyfill to my workflow made it work, so I can do that if necessary but this seems like a bug to me.

`useBuiltIns` just replaces `import "babel-polyfill";` to import of required modules, without it, it will not work.

**Comment by JasonEtco** [comment]
I see; I appreciate the clarification, thanks!

**Comment by hzoo** [comment]
https://github.com/babel/babel-preset-env#usebuiltins you have to include babel-polyfill yourself since there's no easy way for babel to apply it for you.

Looks like you already tried adding it and it works, so closing! The only idea I have is to make a new babel-loader like babel-loader-env that would somehow auto add it to do the entry point for you.

**Comment by nicemaker** [comment]
Have the same problem, but don't understand how to solve it.
I use rollup.js to bundle my files. I installed dependencies like this:

```
npm i rollup-plugin-babel -D
npm i babel-preset-env -D
```
then my *babelrc*:

```
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7","ie >= 10"]
        
      }
      , "useBuiltIns": "entry"
      , "modules": false
    }]
  ],
  "plugins": ["external-helpers"]
}
```

I also tried the above plus:

```
  "include": ["es6.array.find"]
```

No Array.find polyfill in my resulting js file.
What am I missing/missunderstanding?
