### ISSUE TITLE
Problema Error: Couldn't find preset "env" relative to directory "D:\\www\\test\\...."

### ISSUE THREAD

**Issue by EOM** [babel/babel-preset-env#219]
Hi, problema use **Bable to PowerShell in Widows 10 Pro 64Bit**

NodeJs: v6.9.5 **_(Install in C:\ ... \ ...)_**
NPM: v3.10.10 **_(Install in C:\ ... \ ....)_**

Install: **_(Install global in C:\ ... \ ...)_**
`npm install babel babel-cli babel-preset-env babel-core babel-loader babel-preset-es2015 babel-preset-react -g`

**Folders:**
```
D:\www\test\js\test2.es6
D:\www\test\js\.babelrc
```

**File .babelrc:**
```
{
    "presets": [
        "env"//,
        //"es2015"
    ]
}
```

**Use Example:**
`D:\www\test\js> babel .\test2.es6 --out-file test2-compiled.js`
OR
`D:\www\test\js> babel --no-babelrc .\test2.es6 --out-file test2-compiled.js --presets=es2015,react`

**Error Out:** 
`Couldn't find preset "env" relative to directory "D:\\www\\test\\js"`
OR
`Couldn't find preset "es2015" relative to directory "."`

**Note:** The same test with **[Bublé](https://buble.surge.sh/guide/)** and transpilo OK

**Comment by yavorsky** [comment]
¡Hola
Have you seen https://github.com/babel/babel-preset-env/issues/186? It might be relative.

**Comment by EOM** [comment]
Transpiler OK this way

**Install:**
`npm install --save-dev babel-cli babel-preset-es2015`

**Folder:**
`C:\test\test2.es6`

**Use:**
`C:\test>.\node_modules\.bin\babel.cmd .\test2.es6 --out-file test2.js --presets es2015`
OR
`C:\test>.\node_modules\.bin\babel.cmd .\test2.es6 --out-file test2.js --presets es2015 -s test2.js.map`

**Out Ok ;-)**

**Comment by yavorsky** [comment]
@EOM So, installing the preset locally helped?

**Comment by trusktr** [comment]
I can confirm that I get this problem when using npm v2, but no problems when using v4.

More detailed error message: https://github.com/electron-userland/electron-forge/issues/154

**Comment by EOM** [comment]
Now Test OK for

**My Install version**
npm 4.1.2
node v7.7.3
babel --version 6.24.0 (babel-core 6.24.0)

**File: .babelrc**
```
{
    "presets": [
        "env"
    ]
}
```

**_And not install global babel, relative path_**
`.\node_modules\.bin\babel.cmd .... .. ....`
