### ISSUE TITLE
'useBuiltIns' option force to import 'regenerator-runtime'

### ISSUE THREAD

**Issue by revyh** [babel/babel-preset-env#221]
Basicly my `.babelrc` file looks like this:

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions"]
      },
      "modules": false,
      "useBuiltIns": true
    }]
  ],
  "plugins": [
    ["transform-runtime", {
      "polyfill": false,
      "regenerator": true
    }]
  ]
}
```

And then in entry point I use `import 'core-js';`.

The idea is to always import 'core-js' for polyfilling standard library and import helpers and regenerator runtime only when it's really used in code (via 'transform-runtime' plugin). `useBuiltIns` can be great improvement to this scenario that will reduce number of 'core-js' polyfills. But `useBuiltIns` forces to import regenerator runtime if 'transform-regenerator' is included to preset. I don't want to exclude 'transform-regenerator', I want to manage regenerator runtime through 'transform-runtime'.

Maybe it would be better to accept `useBuildIns` as a boolean and as an object?

```json
"useBuiltIns": {
  "polyfill": true,
  "regenerator": false
}
```

**Comment by yavorsky** [comment]
@revyh Hi! Thanks for your proposition. We already have related discussion in https://github.com/babel/babel-preset-env/issues/84.

The problem is that Babel runs per file.
`import 'core-js'` or `import babel-polyfill` is assigning new methods to global objects prototypes like `String`, `Array`, etc and in such way, we will include `import 'core-js/some-feature'` for every module.

Also, instance methods such as "foobar".includes("foo") will not work since that would require modification of existing built-ins.

So, for now, this idea might be implemented only for non-instance methods, for ex. promises or web.immediate. We could exclude it from `transform-polyfill-require-plugin` and create new runtime plugin for such things.

**Comment by hzoo** [comment]
2 things: one you would simply exclude regenerator from the env preset: https://github.com/babel/babel-preset-env#exclude

the other is that you shouldn't be using both babel-polyfill (import core-js) and using transform-runtime because they both do the same thing.

**Comment by revyh** [comment]
@hzoo
1. I use 'transform-runtime' plugin with `polyfill: false` option, wich disables polyfilling standard library. In this case 'transform-runtime' should not conflict with 'core-js' polyfills

2. I want to use 'transform-regenerator' to transform generators syntax (don't want exclude it), but I don't want `useBuiltIns` to always import regenerator runtime. Instead I want 'transform-runtime' to import regenerator runtime only when it's needed (generators actually presents in my code).

@yavorsky If I understand you right, you wrote about customising 'transform-runtime' behaviour by `useBuiltIns` option. I didn't asking about it. Essentially, what I want is:

add some normalization to `useBuiltIns` option

```javascript
// somewhere in 'normalize-options.js'
let useBuiltIns = {
  polyfill: false,
  regenerator: false,
};

if (typeof opts.useBuiltIns === 'boolean') {
  useBuiltIns.polyfill = useBuiltIns.regenerator = opts.useBuiltIns;
} else if (opts.useBuiltIns && typeof opts.useBuiltIns === 'object') {
  useBuiltIns = opts.useBuiltIns;
}
```

and change [this code](https://github.com/babel/babel-preset-env/blob/6ea636f42db4e45ec3bac2cf01a1199eb4b3bfaa/src/index.js#L218-L219) to something like this

```javascript
useBuiltIns.regenerator &&
plugins.push([transformPolyfillRequirePlugin, { polyfills, regenerator }]);
```

and use `useBuiltIns.polyfill` [here](https://github.com/babel/babel-preset-env/blob/6ea636f42db4e45ec3bac2cf01a1199eb4b3bfaa/src/index.js#L180) and [here](https://github.com/babel/babel-preset-env/blob/6ea636f42db4e45ec3bac2cf01a1199eb4b3bfaa/src/index.js#L199)

**Comment by yavorsky** [comment]
@revyh Got it!
Looks like you already have a decision.
Just need to add the additional check to https://github.com/babel/babel-preset-env/blob/master/src/index.js#L207.

**Comment by revyh** [comment]
@yavorsky Thx for quick reply!
Speaking about additional check, I would rather do one `if` statement:

```javascript
if (useBuiltIns.regenerator) {
  const regenerator = transformations.indexOf("transform-regenerator") >= 0;
  plugins.push([transformPolyfillRequirePlugin, { polyfills, regenerator }]);
}
```

**Comment by yavorsky** [comment]
@revyh If I understand correctly:
```js
useBuiltIns: {
  polyfill: true,
  regenerator: false
}
```
won't pass the check and will transformPolyfillRequirePlugin won't be added.

**Comment by revyh** [comment]
yes
