### ISSUE TITLE
Support for CEF (Chromium Embedded Framework) as a target environment

### ISSUE THREAD

**Issue by TrevorSayre** [babel/babel-preset-env#222]
Chromium Embedded Framework
https://bitbucket.org/chromiumembedded/cef

CEF 3 is currently used as a the environment for Adobe CEP, a way for third-parties and individual users to write embedded panels for all Adobe products:
https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_7.x/CEP_7.0_HTML_Extension_Cookbook.pdf

 -|CEP 5.2|CEP 6.1 and CEP 7.0
---|---|---
CEF 3|CEF 3 branch 1453, revision 1339|CEF 3 release branch 2272 Commit e8e1f98ee026a62778eb2269c8e883426db645ea
Chromium|27.0.1453.110|41.0.2272.104
Node.js|Node.js 0.8.22|IO.js 1.2.0
CEF/Node integration|cefnode ?|Node-WebKit 0.12.1 (nw.js)

**Comment by hzoo** [comment]
Sure we can do this, just need a way to map the CEF version to node/chrome for each version, and how to update in the future. for chromium we now have a separate package to get updated https://github.com/Kilian/electron-to-chromium

**Comment by darahak** [comment]
This is something I'd be interested in.
@hzoo Should we make a `cef-to-chromium` package?

**Comment by TrevorSayre** [comment]
@darahak Thanks for taking a look. Anything I can provide to help?

**Comment by darahak** [comment]
@TrevorSayre Initially, I wanted to take a look at [electron-to-chromium](https://github.com/Kilian/electron-to-chromium) and see what could be done for CEF, but I didn't even have time to do that.

The only thing I looked at is the way CEF builds are versioned, which is a bit particular:
> Modern CEF release version numbers have the format X.YYYY.A.gHHHHHHH where:
> - "X" is the CEF major version (currently 3).
> - "YYYY" is the Chromium branch.
> - "A" is an incremental number representing the number of commits in the current branch. This is roughly equivalent to the SVN revision number but on a per-branch basis and assists people in quickly determining the order of builds in the same branch (for bug reports, etc).
> - "gHHHHHHH" is the 7-character abbreviation for the Git commit hash. This facilitates lookup of the relevant commit history in Git.

**Comment by TrevorSayre** [comment]
So then the currently used CEF in all Adobe panel products is:
`3.2272.???.e8e1f98`

That would be at commit `e8e1f98ee026a62778eb2269c8e883426db645ea`
Located in the repo at:
https://bitbucket.org/chromiumembedded/cef/commits/e8e1f98ee026a62778eb2269c8e883426db645ea

Based on the branch:
https://bitbucket.org/chromiumembedded/cef/branch/2272

It looks like it would be:
`3.2272.27.e8e1f98`

This is so idiosyncratic...
