### ISSUE TITLE
Environment "browser" and version "latest"

### ISSUE THREAD

**Issue by AlicanC** [babel/babel-preset-env#23]
It would be nice if we had a "browser" environment which would cover all browsers and a "latest" version to target the latest version of an environment.

Examples:

``` javascript
{ browser: 'latest' }
// =>
{ chrome: 'latest', edge: 'latest', firefox: 'latest', safari: 'latest' }
// =>
{ chrome: 123, edge: 123, firefox: 123, safari: 123 }
```

**Comment by hzoo** [comment]
There's https://github.com/babel/babel-preset-env/pull/19 which I believe covers this?

**Comment by AlicanC** [comment]
Not really. #19 just adds a special field (browsers) that uses browserslist. What I am suggesting is a solution for all fields (browsers, chrome, node, etc.).

**Comment by hzoo** [comment]
In a previous issue we asked if browser list would also add in node as well. I'm not sure you actually want latest for everything on the compat-table

**Comment by yavorsky** [comment]
I think, we can extend https://github.com/babel/babel-preset-env/pull/19 according to this needs. Just parse implicit fields using browserslist if type of the field is a string, for ex.

**Comment by AlicanC** [comment]
> I'm not sure you actually want latest for everything on the compat-table

You might not, but when you have it for browsers and not Node.js the configuration becomes weird:
```json
{
  "browsers": "latest 2 versions", OK
  "ie": "latest 3 versions", OK
  "node": "latest 2 versions" Error?
}
```

Type of the configuration looks like this:
```javascript
type VersionNumber = number;
type BrowserslistQuery = string;

type Configuration = {
  browsers: Array<BrowserslistQuery>,
  edge: VersionNumber | BrowserslistQuery,
  chrome: VersionNumber | BrowserslistQuery,
  node: VersionNumber,
};
```

This is very inconsistent.

**Comment by hzoo** [comment]
I was saying Node could be added - https://github.com/babel/babel/pull/3476#issuecomment-237872462

**Comment by chicoxyzzy** [comment]
browserlist's issue to track https://github.com/ai/browserslist/issues/75

**Comment by amilajack** [comment]
https://github.com/babel/babel-preset-env/pull/19 was merged. Should this be closed?
