### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by cazzer** [babel/babel-preset-env#238]
### Issue
After updating to `v1.3.0` I get the following error when `babel`ing my code:
`Error: Cannot find module 'semver' (While processing preset: "/tmp/src812613487/src/node_modules/babel-preset-env/lib/index.js")`.

### Workaround
Lock down your version to `v1.2.2` and grab a beer.

### Context
I'm running this alongside
- `babel@6.24.0`
- `npm@3.10.8`
- `node@v6.9.1`

**Comment by hzoo** [comment]
Looks like the published version is incorrect, should be an easy fix

**Comment by hzoo** [comment]
`"prepublish": "npm run build"`

Try v1.3.2

**Comment by citycide** [comment]
Fixed it for me. Thanks!

**Comment by existentialism** [comment]
@citycide sorry for the trouble!

**Comment by citycide** [comment]
@existentialism no worries. Branches become forests.

> for git is dark, and full of terrors.
