### ISSUE TITLE
PSA: ask other preset repos (if they are willing) to deprecate in favor of this preset

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#239]
There were a few reasons we finally started preset-env (much in https://github.com/babel/babel/pull/3476). One of the reasons was similar to the problem that presets never had the ability to provide it's own options. After we added options to preset-es2015 (loose mode, modules: false for webpack, etc), it removed the need for presets like `preset-es2015-loose` and `preset-es2015-webpack` and even `preset-es2015-loose-webpack`, etc.

Now another problem that has been emerging is the proliferation of presets like `babel-preset-es2015-chrome-43` which is oddly specific. My ask is that we all work to improve one preset as the base for these kinds of things since we can all help to use/maintain it. 🙏

And if preset-env is compiling when it shouldn't then check the data on https://github.com/kangax/compat-table and/or https://github.com/babel/babel-preset-env/blob/master/data/plugins.json. (Just because it parses correctly doesn't mean the feature is supported fully btw)

---

> This is going to take a lot of effort, thanks in advance for any help! 🙌

So the goal: 
- [ ] Search for [`babel-preset` on libraries.io](https://libraries.io/search?q=babel-preset) or [npm](https://www.npmjs.com/search?q=babel-preset)
- [ ] check that the preset is related to a specific environment (chrome, node, modern, etc) even if it has es2015, es2016, in the name. If it's just someone's custom preset (not in the name) then there's no need to do anything (unless you want to recommend env to them 😄)
- [ ] make sure it's not already deprecated or has an issue open about this
  - [ ] also check that they are running `npm deprecate` if they didn't know about it. You can test this by simply doing `npm install pkg` to see if a warning comes out
- [ ] create an issue and **link** to this issue explaining that we are asking as the Babel maintainers for these kinds of presets to be deprecated in favor of using preset-env. Of course they don't have to do this but I'd hope that many would rather do that than maintain or have to create a new preset later.

---

Deprecation steps (my suggestions):

<img width="633" alt="screen shot 2017-03-30 at 10 39 31 pm" src="https://cloud.githubusercontent.com/assets/588473/24534117/e79c6c4a-1599-11e7-8fce-51b1d82f4b02.png">

- [ ] Suggest editing the description of the repo to say `[Deprecated] description here` and add a github topic called `deprecated`
- [ ] tell the package author to run `npm deprecate pkg-name-here "message here"`, where message here explains that preset-env covers exactly what the preset did before and will be maintained/updated by the community and the Babel team and to link to the readme explaining for information or even this issue.
- [ ] Suggest adding a large heading that says the repo is deprecated and link to preset-env as the recommendation and if you wanted add a deprecated "badge"
- [ ] Even better, explain how to convert the config to the new one using preset-env and the install steps 

Example for if the preset was specifically for chrome 43 (https://www.npmjs.com/package/babel-preset-chrome-43):

Installation

```js
npm install babel-preset-env --save-dev
yarn add babel-preset-env --dev
```

before

```json
{
  "presets": ["chrome-43"]
}
```

`.babelrc Configuration`

```js
{
  "presets": [
    ["env", {
      "targets": {
        "chrome": 53
      }
    }]
  ]
}
```

---

This is going to take a while so you don't necessarily have to say "I'm doing this", I think linking to this issue will help us see which issues are opened/closed.

**Comment by hzoo** [comment]
Examples:

https://github.com/jakepusateri/auto-babel/commit/cd6353b429954083e49b596296938f70fc7e6c18
https://github.com/sdkennedy/babel-preset-target/issues/1
https://github.com/bkonkle/babel-preset-es2015-loose/issues/13

**Comment by aaronang** [comment]
If no one is going to take this issue in one week (too long?), I will take the responsibility 😬

**Comment by agirton** [comment]
Hi @hzoo, I am about to go on vacation so I didn't have time to write a bot this weekend to open a PR on each of these. Each repo would roughly get the same message but with different babel config changes.

Another option would be just to open an issue and have the user make the changes. The downside is it requires the owner to do this instead of a quick approve. Here is the message I was going to use, let me know if this is not clear enough.

> Hello!
>
> We noticed you are using babel-presets, this is great! However, now that we have [babel-preset-env](https://github.com/babel/babel-preset-env) users can set the environment they are targeting and the package will handle loading the proper plugins and polyfills needed.
>
> Would you consider deprecating this package and point users to `babel-preset-env`? This PR adds the deprecation and the migration path.
>
>
> ```
> ### [Deprecated] This package is now deprecated in favor using the new [babel-preset-env](https://github.com/babel/babel-preset-env) package. Here is how to migrate:
> 
> Install 
> npm install babel-preset-env --save-dev
> yarn add babel-preset-env --dev
> 
> Before
> {
>   "presets": ["chrome-43"]
> }
> 
> After:
> {
>   "presets": [
>     ["env", {
>       "targets": {
>         "chrome": 53
>       }
>     }]
>   ]
> }
> ```
>
>
> If you have an further questions or need some more context see this [issue](https://github.com/babel/babel-preset-env/issues/239).

**Comment by hzoo** [comment]
This is awesome!!

> We noticed you are using babel-presets, this is great!

I think this can be worded differently? It's not really about using babel-presets but making or creating/publishing one.

But yeah the point is that the preset they have made is covered completely by preset-env with an option. So if it's chrome 43, then it's not really necessary as a 3rd party preset.

**Comment by agirton** [comment]
Hey @hzoo, I updated the first paragraph. How does this sound? See below: 

> Hello!
>
> We noticed you created/published a babel-preset, this is great! However, now that we have [babel-preset-env](https://github.com/babel/babel-preset-env), this specific preset is covered completely by preset-env. Users can set the environment they are targeting and the package will handle loading the proper plugins and polyfills needed.
>
> Would you consider deprecating this package and point users to `babel-preset-env`? This PR adds the deprecation and the migration path.
>
>
> ```
> ### [Deprecated] This package is now deprecated in favor using the new [babel-preset-env](https://github.com/babel/babel-preset-env) package. Here is how to migrate:
> 
> Install 
> npm install babel-preset-env --save-dev
> yarn add babel-preset-env --dev
> 
> Before
> {
>   "presets": ["chrome-43"]
> }
> 
> After:
> {
>   "presets": [
>     ["env", {
>       "targets": {
>         "chrome": 53
>       }
>     }]
>   ]
> }
> ```
>
>
> If you have any further questions or need some more context see this [issue](https://github.com/babel/babel-preset-env/issues/239).

**Comment by aaronang** [comment]
@agirton Could you maybe elaborate more on what the pull request would contain? What specific changes would it contain? What do you mean with "the deprecation and the migration path"? 

Additionally, what did you have in mind for a bot? In my opinion, it would be pretty difficult to determine whether the "custom preset" functionality is covered by `babel-preset-env`. Please correct me if I am wrong.

By the way, have enjoy your vacation 🎉

**Comment by agirton** [comment]
Hi @aaronang, thank you for reviewing! The PR would only be an update to the README. Which would include the deprecation message and the steps the user would have to migrate away from the old preset.

I agree that writing a bot may be difficult to do based on all the variances and may not be worth the time. My first thought would be to first search `npms.io` or some other fast npm search with something like `https://api.npms.io/v2/search?q=babel-preset- not:deprecated` which would return all non deprecated packages with the babel-preset. Then I would need to go to github with each one and check the package if it's covered or not. I would know what files to walk through based on the file in `package.json`.

Thoughts?

**Comment by hzoo** [comment]
@agirton I tried to explain above that the presets would only be specific ones

> check that the preset is related to a specific environment (chrome, node, modern, etc) even if it has es2015, es2016, in the name. If it's just someone's custom preset (not in the name) then there's no need to do anything (unless you want to recommend env to them 😄)

We don't need to check the package.json, just check the name - it can be done manually too. Just need to search if the name has "chrome" or "node" or "es6" or "loose", etc in it.

**Comment by agirton** [comment]
@hzoo sorry for the confusion, I should clarify what I mean by checking the `package.json`. The bot would find the main file to search so that way it could put in a customized migration for the user.

Matter of fact if the owner documented it, we would only need to grab the code from the `README`. For example, If the bot made a PR on the `babel-preset-es2015-node` package it would update the README with this migration path:

```
Before
{
  "presets": ["es2015-node"]
}

After:
{
  "presets": [
    ["env", {
      "targets": {
        "node": 4
      }
    }]
  ]
}
```

But again, this may be better just to manually do this because of the amount of variants.

**Comment by jaydenseric** [comment]
Ideally v2 will ship soon, before a lot of these migration suggestions go out. That way we can recommend just using engines or browserslist config, and if they specify a version for some reason it will be a string, not an int.
