### ISSUE TITLE
Move transform-runtime functionality into this preset

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#246]
After https://github.com/babel/babel-preset-env/pull/241 is done

The plugin that is added is a fork of transform-runtime to only do polyfills but it's very similar logic so we could just make it an option, maybe `useBuiltIns: runtime`.

Then we can deprecate that plugin and make everything simplier.

**Comment by pixelass** [comment]
Any news on this?

**Comment by epiloque** [comment]
@hzoo this would be very nice :eyeglasses::bowtie:

**Comment by callamwilliams** [comment]
Bump

**Comment by paveleremin** [comment]
any updates?
