### ISSUE TITLE
Allow configuring target ES version

### ISSUE THREAD

**Issue by Reinmar** [babel/babel-preset-env#250]
I don't know if this issue will make any sense but let's try :)

I have my code in ES6 and I don't plan to use ES7+. When I use babel-preset-env my guess is that it loads plugins for ES7+ features, which may slow down the build process.

If I were able to set the target ES version to ES6, then `babel-preset-env` would be able to load just the plugins I really need.

**Comment by hzoo** [comment]
Loading "ES7" isn't going to be much slower, if everyone thinks this is is necessary we can consider it. This is basically https://github.com/babel/babel-preset-env/issues/91

**Comment by Reinmar** [comment]
I guess you must be right that transpiling ES7 won't be much slower now, but what if more and more ESx versions will be released? In the future, if you have legacy settings like "browsers from 2017", there may be dozens of plugins enabled.

**Comment by hzoo** [comment]
If you don't write that syntax it won't be slower to build, loading plugins doesn't make it slow

**Comment by hzoo** [comment]
Closing since "visiting" nodes that aren't actually in the code isn't slower and loading plugins isn't the bottleneck. We are also going to work on plugin ordering later so that won't be an issue
