### ISSUE TITLE
Default Behavior Different Than Latest Preset

### ISSUE THREAD

**Issue by andrewjmead** [babel/babel-preset-env#256]
Thanks for putting together babel-preset-env. It's fantastic.

The docs mention the the "default behavior without options is the same as babel-preset-latest". I ran a simple CLI example and I am indeed getting different results. I'm sure it's on my end, I'd just love some clarification on this.

Here's the simplest possible recreation (2 files in the same directory):

**package.json**
```
{
  "scripts": {
    "withEnv": "babel script.js --presets env",
    "withLatest": "babel script.js --presets latest"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-env": "^1.3.2",
    "babel-preset-latest": "^6.24.1"
  }
}
```

**script.js**
```
const one = 123;
one = 432;
console.log(one);
```

If you run `npm run withEnv` you won't get a single error (not expected). Babel will dump the output to the console.

If you run `npm run withLatest` you'll get an error related to the variable "one" being read-only (expected).

Any idea why I'm getting different results here? Thanks for your time.

\- Andrew

**Comment by existentialism** [comment]
@andrewjmead thanks for the report! Pretty sure the problem is plugin ordering... the constant-check plugin needs to run before block-scoping turns it into a var :)

Will push a fix!

**Comment by andrewjmead** [comment]
Thanks for the fast response. I really appreciate it.

Feel free to let me know when it up. I'd be happy to test!

**Comment by hzoo** [comment]
wow a perfect reason why we need to handle plugin ordering correctly

**Comment by existentialism** [comment]
@andrewjmead published https://github.com/babel/babel-preset-env/releases/tag/v1.3.3 which includes the fix!

**Comment by andrewjmead** [comment]
Fix worked for me! Thanks for taking care of this so quick.

**Comment by hzoo** [comment]
FYI made https://github.com/babel/babel/issues/5623 to discuss plugin ordering
