### ISSUE TITLE
Node.js 6.10 is being detected as 6.1

### ISSUE THREAD

**Issue by witq** [babel/babel-preset-env#261]
Because the current node.js version is computed using `parseFloat`, node.js versions with major or minor versions ending with 0 are misinterpreted. I noticed this when testing various versions of node and getting more transforms when using node 6.10 than with node 6.9.
I think that node.js versions should be stored as strings and then `semver` could be used for version comparisons.
Would you be interested in a pull request implementing this?

**Comment by existentialism** [comment]
@witq thanks for the issue! we've actually [already implemented](https://github.com/babel/babel-preset-env/pull/231) in the soon to be released 2.x version.

**Comment by existentialism** [comment]
@witq just released [v1.5](https://github.com/babel/babel-preset-env/releases/tag/v1.5.0) that should resolve this!
