### ISSUE TITLE
get confused about this preset, how should I use this with transform-runtime plugin?

### ISSUE THREAD

**Issue by lili21** [babel/babel-preset-env#267]
do I need `transform-runtime` plugin ?

do I need to import polyfill by myself ?

what is the recommend config now ?

can't make this work with or without `transform-runtime` plugin, and the `browserlist` in `package.json` looks like be ignore.

**Comment by hzoo** [comment]
We can't import the polyfill for you - check the docs for https://github.com/babel/babel-preset-env#usebuiltins. It may change in 2.0 but you should try import the polyfill at the entry point. 

> and the browserlist in package.json looks like be ignore.

It's not supported yet https://github.com/babel/babel-preset-env/pull/161

Thanks for making an issue! However, issues are not for support questions but rather for reporting bugs/features requests.

If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
