### ISSUE TITLE
Guide to contribute to compat-table for env purposes

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#27]
Can writeup the steps (pictures, etc) to add a new feature to a browser/env to https://kangax.github.io/compat-table/es6/.

Explaining how [exports.browsers works](https://github.com/kangax/compat-table/blob/cc3311ca53d1d3e1e298f9eea0d24d2c43f6e8a7/data-es6.js#L36) etc

**Comment by chicoxyzzy** [comment]
Actually it's too early to write any guides for compat-table because it will change a lot in nearest future but we definitely will need some guides.

**Comment by hzoo** [comment]
Ok 👍 , can move this issue to that repo anyway
