### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by evilebottnawi** [babel/babel-preset-env#277]
Package contains unnecessary directories and files - `coverage`, `.eslintrc` and maybe others. I can do PR if your accept this issue.

**Comment by hzoo** [comment]
Sure. just add coverage/.eslintrc to https://github.com/babel/babel-preset-env/blob/master/.npmignore. The only other one would be contributing.md

**Comment by hzoo** [comment]
Closed in https://github.com/babel/babel-preset-env/issues/281
