### ISSUE TITLE
Classes coupled with stage-0 function improperly without including transform-es2015-classes

### ISSUE THREAD

**Issue by eliperelman** [babel/babel-preset-env#292]
Using preset-env 1.4.0 and stage-0 with the following options:

```js
{ modules: false,
  useBuiltIns: true,
  targets:
   { browsers:
      [ 'last 2 Chrome versions',
        'last 2 Firefox versions',
        'last 2 Edge versions',
        'last 2 Opera versions',
        'last 2 Safari versions',
        'last 2 iOS versions' ] } }
```

When used with the following React class, clicking on the button throws errors about `setState`, most likely from some sort of scope or binding issue:

```jsx
import React, {Component} from 'react';

export default class App extends Component {
    state = {
        count: 0,
    };

    handleClick = () => {
        this.setState({
            count: this.state.count + 1,
        })
    }

    render() {
        return (
            <div>
                <p>Count: {this.state.count}</p>
                <button onClick={this.handleClick}>Increase Count</button>
            </div>
        )
    }
}
```

Error, for context (in Chrome 57):

<img width="566" alt="screen shot 2017-04-17 at 8 54 11 am" src="https://cloud.githubusercontent.com/assets/285899/25090889/771217c6-234b-11e7-95d2-e4f2a19690a2.png">

If I manually include `transform-es2015-classes`, the problem goes away, and clicking the button executes the `setState` as desired.

It seems that using these browser targets should support classes in this manner when combined with stage-0, but throw errors unless the classes transform is there. Thoughts? Thank you!

This is a follow-up from https://github.com/mozilla-neutrino/neutrino-dev/issues/172.

**Comment by existentialism** [comment]
@eliperelman I couldn't repro this locally or via [webpackbin](https://www.webpackbin.com/bins/-KiCXvFZTJHfnt2Ei_iT).

After digging into this a bit, the issues seem to go away if I disable `react-hot-loader` in the example posted on the issue you linked.

**Comment by eliperelman** [comment]
@existentialism you're totally correct, removing react-hot-loader resolved the issue. Closing. Thanks!

**Comment by eliperelman** [comment]
For posterity, this appears to be the related issue:

https://github.com/gaearon/react-hot-loader/issues/313
