### ISSUE TITLE
Env specific modules options

### ISSUE THREAD

**Issue by pascalduez** [babel/babel-preset-env#296]
Hi,

I would like to generate two different builds, one transpiled to `commonjs` modules and one keeping ES2015 modules.

I'm trying to make this work with an `env` override:

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "> 1%"],
        "node": "current"
      },
    }],
  ],
  "env": {
    "ESM": {
      "presets": [
        ["env", {
          "targets": {
            "browsers": ["last 2 versions", "> 1%"],
            "node": "current"
          },
          "modules": false,
          "debug": true,
        }],
      ],
    },
  },
}
```
```
BABEL_ENV=ESM babel src/ -d dist/
```

Alhtough the debug informations properly prints `Modules transform: false` the modules are still compiled to commonjs.

Also I need to set the `targets` option twice, otherwise it's lost and result in an empty object.
 
Am I missing something obvious? 
What would be the best direction to be able to ship a package with both modules "styles".
Having a `main` and a `module` key in package.json.

**Comment by pascalduez** [comment]
Funny thing is it works **the other way round**:

```js
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "> 1%"],
        "node": "current"
      },
      "modules": false,
    }],
  ],
  "env": {
    "CJS": {
      "presets": [
        ["env", {
          "targets": {
            "browsers": ["last 2 versions", "> 1%"],
            "node": "current"
          },
          "debug": true,
        }],
      ],
    },
  },
}
```

Prints `Modules transform: commonjs` and modules are properly compiled to commonjs.

**Comment by pascalduez** [comment]
This is how I ended up: https://github.com/pascalduez/react-module-boilerplate/pull/1

**Comment by hzoo** [comment]
Yeah, we are deprecating the "env" key in the config in favor of a .babelrc.js file in Babel 7 so something like what you did should work. Example of what we are doing in Babel itself with Babel 7 alpha https://github.com/babel/babel/blob/7.0/.babelrc.js#L24
