### ISSUE TITLE
Not transforming { get } for node 4 support

### ISSUE THREAD

**Issue by m59peacemaker** [babel/babel-preset-env#299]
.babelrc
```json
{
  "presets": [
    [ "env", {
      "targets": { "node": 4 }
    } ]
  ]
}
```

src.js
```js
const get = 123
const x = {
  get
}
```

build.js
```
"use strict";

var get = 123;
var x = {
  get
};
```

This is not transpiled properly for node 4 and will throw unexpected token. However, if I transpile for node 0.12, it is transpiled correctly to what node 4 also needs:

```js
"use strict";

var get = 123;
var x = {
  get: get
};
```

I've tried multiple babel/plugin versions.

**Comment by yavorsky** [comment]
@m59peacemaker Hi! Thanks for the issue.

`Object shorthand properties` is implemented in node.js 4. See: https://kangax.github.io/compat-table/es6/#test-object_literal_extensions

In your case, you are trying to initialize object with `get` property. node.js has a bug with shorthand `get `/`set` properties. (I will find related issue when I have more time, sorry). So you can just avoid this or use the different variable name if it's possible.

But seems like people could use Babel to avoid this bug and without transformation, it becomes harder. Maybe we should add an exception for preset-env or send a PR to `compat-table` by adding this case to `object literal extensions` section to reduce node.js coverage.

cc @chicoxyzzy
