### ISSUE TITLE
v1.4.0 Unexpected token ...

### ISSUE THREAD

**Issue by ssfernando** [babel/babel-preset-env#303]
I'm getting syntax error using rest parameters on **node version 7.9**

**package.json:**
```
"devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-env": "^1.4.0",
```

**.babelrc:**
```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      },
      "exclude": ["transform-async-to-generator"]
    }]
  ],
  "sourceMaps": true,
  "retainLines": true
}
```

**Comment by loganfsmyth** [comment]
Maybe a duplicate of https://github.com/babel/babel/issues/5648 ? You haven't told us what code causes the error, so it is hard to say.

**Comment by ssfernando** [comment]
@loganfsmyth You rigth, my mistake, here the code:

```
static async byMerchantId(merchantId, merchantName) {
    try {
      const offersDb = await Offer.findAllByMerchantId(merchantId)
      const rest = await this.commonData()
      return { offersDb, merchantId, merchantName, firstLine: true, ...rest }
    } catch (e) {
      throw e
    }
  }
```
->> { offersDb, merchantId, merchantName, firstLine: true, **-> ...rest** }

But I don't think it is a duplication of [babel/babel#5648](https://github.com/babel/babel/issues/5648)

My goal is actualy have the babel not transpiling it, since it is supported by Node v7.9:
![image](https://cloud.githubusercontent.com/assets/802541/25271960/cd6a1206-267d-11e7-95b6-1e2d11ff15ca.png)

**Comment by danez** [comment]
Do you know where the error message is coming from? Or do you have a stacktrace? It doesn't seem to come from babel, so I wonder if there some other tool  involved that does not understand object spread.

**Comment by ssfernando** [comment]
Closing the issue. Rest parameter is supported just in function arguments and spread ... operator just in arrays.

**Comment by ssfernando** [comment]
@danez The error was that:

```
fernando$ ./node_modules/.bin/babel src -d dist -s
src/config/hash.js -> dist/config/hash.js
src/factory/modelFactory.js -> dist/factory/modelFactory.js
src/index.js -> dist/index.js
............. other files
src/service/importCSV.js -> dist/service/importCSV.js
SyntaxError: src/service/memoryData/memoryData.js: Unexpected token (10:68)
   8 |       const offersDb = await Offer.findAllByMerchantId(merchantId)
   9 |       const rest = await this.commonData()
> 10 |       return { offersDb, merchantId, merchantName, firstLine: true, ...rest }
     |                                                                     ^
  11 |     } catch (e) {
  12 |       throw e
  13 |     }
```

Using transform-object-rest-spread plugin solves the problem

.babelrc:
```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      },
      "exclude": ["transform-async-to-generator"]
    }]
  ],
  "plugins": ["transform-object-rest-spread"],
  "sourceMaps": true,
  "retainLines": true
}
```

**Comment by hzoo** [comment]
^ object rest spread is still stage 3 so it's not included in preset-env https://github.com/babel/babel-preset-env#support-all-plugins-in-babel-that-are-considered-latest
