### ISSUE TITLE
Can't build project with latest core-js

### ISSUE THREAD

**Issue by alexeyraspopov** [babel/babel-preset-env#304]
I've created a gist that you can clone with minimum environment for reproducing:
https://gist.github.com/alexeyraspopov/4b4c5b581ae4a0795370bf8894acda67

I use Babel 6.24 and Env 1.4 and here what I see after I attempt to use Babel Polyfill:

```
ERROR in ./index.js
Module not found: Error: Can't resolve 'core-js/modules/es7.string.pad-start' in '/Users/alexey/oss/wtf'
 @ ./index.js 193:0-47
 @ multi (webpack)-dev-server/client?http://localhost:8080 .

ERROR in ./index.js
Module not found: Error: Can't resolve 'core-js/modules/es7.string.pad-end' in '/Users/alexey/oss/wtf'
 @ ./index.js 195:0-45
 @ multi (webpack)-dev-server/client?http://localhost:8080 .
```

cc @yavorsky

**Comment by hzoo** [comment]
https://unpkg.com/core-js@2.4.1/modules/es7.string.pad-start.js

babel-polyfill needs to be a dependency https://github.com/babel/babel-preset-env#usebuiltins, and you should be good!

**Comment by GProst** [comment]
Hi @hzoo!

I have a similar problem, described in [this comment](https://github.com/callstack/haul/issues/140#issuecomment-310098741). `core-js` of version `^1.0.0` is installed in the upper `node_modules` directory. Which somehow causes described error, although `babel-pilyfill` contains its own `core-js` of version `^2.5.0`. If I do not include `import 'babel-polyfill'` in my index.jsx webpack builds fine.

Is there a way to resolve this without specifying `core-js` in dependencies directly?
