### ISSUE TITLE
Issue with async methods using super for Node < 7.5.0

### ISSUE THREAD

**Issue by julien-f** [babel/babel-preset-env#308]
To be more precise, the issue appears when `super` is supported but async functions are not.

[See this snippet on Babel REPL](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=false&presets=env&targets=Node-6.9&browsers=&builtIns=false&debug=false&code=class%20B%20extends%20A%20%7B%0A%20%20async%20foo%20()%20%7B%0A%20%20%20%20return%20await%20super.foo()%0A%20%20%7D%0A%7D).

As you can see, `super` is used in an incorrect context.

**Comment by julien-f** [comment]
Probably duplicate of babel/babel#3930.

**Comment by xtuc** [comment]
Yes, it looks like a duplicate of that issue. Do you mind if I close this issue? The issue comes from Babel not babel-preset-env.

**Comment by julien-f** [comment]
Nope, thanks for your answer :)
