### ISSUE TITLE
How to use .browserslistrc with [v1] ?

### ISSUE THREAD

**Issue by DimaRGB** [babel/babel-preset-env#311]
I use .browserslistrc for autoprefixer and want to do this with **awesome** babel-preset-env.

So, maybe somebody have any ideas how to use .browserslistrc or browserslist package.json section now for v1 ?

Or need just *copy paste* to `browsers` target option in .babelrc and waiting for [161](https://github.com/babel/babel-preset-env/pull/161)?

Thank you for any answers.

**Comment by yavorsky** [comment]
@DimaRGB Thanks for your issue! We already have a PR https://github.com/babel/babel-preset-env/pull/161
And a few issues with discussion to support it:
https://github.com/babel/babel-preset-env/issues/108
https://github.com/babel/babel-preset-env/issues/26

**Comment by DimaRGB** [comment]
@yavorsky thanks, i will be waiting for merging the PR.
