### ISSUE TITLE
Object.assign not being polyfilled for IE9

### ISSUE THREAD

**Issue by davidhouweling** [babel/babel-preset-env#314]
Hi, i'm using babel-loader with the following configuration but it doesn't appear to be polyfilling Object.assign accordingly (in IE 11). This is the rule i've set up for webpack to pass into babel-loader.

``` js
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          presets: [
            'react',
            ['env', {
              targets: {
                ie: 9,
              },
              modules: false,
              loose: true,
            }],
          ],
        },
      }
```

I would of expected Object.assign to be polyfilled as I know for certain none of the IEs have it. 

I understand I can use the 'include' option, but that seems to defeat the purpose. I thought the idea was that you could use this preset and avoid needing to include babel-polyfill, or having to directly pick out the es6 features.

Am I missing something here?

**Comment by existentialism** [comment]
The plugin actually _transforms_ `babel-polyfill` into only the polyfills your target's need via the [`useBuiltIns`](https://github.com/babel/babel-preset-env/#usebuiltins) option.

**Comment by hzoo** [comment]
@davidhouweling it doesn't do it automatically. You need it babel-polyfill to be a dependency + you need an import of it in your entry point.

> I thought the idea was that you could use this preset and avoid needing to include babel-polyfill. I would check our docs again https://github.com/babel/babel-preset-env#usebuiltins
