### ISSUE TITLE
Node 7.10 is being parsed as Node 7.1

### ISSUE THREAD

**Issue by sheepsteak** [babel/babel-preset-env#315]
When passing `7.10` for `targets.node` the plugins for `7.1` are used instead. I guess it's because it's a number and the zero gets removed?

**Comment by existentialism** [comment]
@sheepsteak thanks for the issue! we've actually [already implemented this](https://github.com/babel/babel-preset-env/pull/231) in the soon to be released 2.x version. (Also ref: https://github.com/babel/babel-preset-env/issues/187, https://github.com/babel/babel-preset-env/issues/261)

**Comment by sheepsteak** [comment]
OK, great! 👍 

Sorry, I just searched for problems with Node rather than targets as strings in general.

**Comment by existentialism** [comment]
@sheepsteak just released [v1.5](https://github.com/babel/babel-preset-env/releases/tag/v1.5.0) that should resolve this!
