### ISSUE TITLE
babel-preset-env how compile es6 only ?

### ISSUE THREAD

**Issue by retyui** [babel/babel-preset-env#316]
I'm trying to make two assemblies,
First only for browsers that support es6 (https://gist.github.com/retyui/71a4ad502e6ff4d05d8f07cd52dd5022)

But I can not disable compilation in es5
```js
{
	loader: 'babel-loader',
	options: {
		"presets": [
			["env", {
				"debug":true,
				"modules": false,
				"loose": true,
				"targets": {
					"browsers": options.es6? "chrome >= 59" : packageJson.browserslist
				}
			}]
		],
		"plugins": [
			"syntax-dynamic-import"
		]
	}
}
```
if es6 `chrome >= 59` else package.json#browserslist : 
```json
[
    "Chrome >= 59",
    "Firefox >= 38",
    "Edge >= 12",
    "Explorer >= 10",
    "iOS >= 8",
    "Safari >= 8",
    "Android 2.3",
    "Android >= 4",
    "Opera >= 12"
  ]
```

**Comment by milesj** [comment]
This may be a bit hacky, but `node: 6.5` is 100% ES6 features, so you can use that as a target.

**Comment by retyui** [comment]
@milesj Omg!! it work ) Спасибо ♥
