### ISSUE TITLE
[error in es2015-loose] inheritance class with get properties

### ISSUE THREAD

**Issue by allangomessl** [babel/babel-preset-env#317]
```
class Parent {
  constructor(props) {
    this.props = props
  }
  get display() {
    return this.props.test // [ERROR] props is undefined when is `get method` and `loose mode`
  }
}

class Child extends Parent {
  get display() {
    return super.display + ' - override'
  }
}
console.log(new Child({ test: 'My Test Property' }).display)
```

### display
`es2015` = `My Test Property - override`
`es2015-loose` = `Cannot read property 'test' of undefined`

link simulation below:
https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015-loose%2Ces2017%2Creact&targets=&browsers=chrome%20%3E%2057&builtIns=false&debug=true&code=class%20Parent%20%7B%0A%20%20constructor(props)%20%7B%0A%20%20%20%20this.props%20%3D%20props%0A%20%20%7D%0A%09get%20display()%20%7B%0A%09%09return%20this.props.test%0A%20%20%7D%0A%7D%0A%0Aclass%20Child%20extends%20Parent%20%7B%0A%09get%20display()%20%7B%0A%09%09return%20super.display%20%2B%20'%20-%20override'%0A%20%20%7D%0A%7D%0Aconsole.log(new%20Child(%7B%20test%3A%20'asdads'%20%7D).display)&experimental=true&loose=false&spec=false

**Comment by loganfsmyth** [comment]
This is the behavior you are opting into currently by using `loose` mode for classes: https://github.com/babel/babel/tree/7.0/packages/babel-plugin-transform-es2015-classes#method-assignment

Unless you've got a really good reason to use `loose` we don't generally recommend it.

**Comment by existentialism** [comment]
Closing since there's not much actionable here wrt preset-env... @allangomessl if you're still having issues and think it's a bug, might want to drop us a line in slack!
