### ISSUE TITLE
es7.array.includes not being detected?

### ISSUE THREAD

**Issue by carldunham** [babel/babel-preset-env#318]
Trying to get this to work, including adding it to `includes`. Babel REPL shows a simple case, happy to provide better example if needed:

[Babel REPL example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=env&targets=Node-4.2&browsers=ie%206&builtIns=false&debug=true&code=%5B1%2C%202%2C%203%5D.includes(2)%3B)

**Comment by darahak** [comment]
Isn't it working as expected? I mean, `Array.prototype.includes` will just get polyfilled so you won't see any difference in the output.

**Comment by carldunham** [comment]
Sorry, my bad. I came to this the long way through an error in some nyc/mocha tests failing. Turned out it was that I wasn't including `babel-polyfill` in the nyc `requires` array.

**Comment by nodkz** [comment]
Confirming that `includes` does not transformed for node 4:
```js
{
  "plugins": [
    "transform-object-rest-spread",
    "transform-flow-strip-types"
  ],
  "presets": [
    ["env", {
      "targets": {
        "node": 4
      },
      "debug": true,
    }]
  ],
}
```

Debug: 
```
Using plugins:
  check-es2015-constants {"node":"4"}
  transform-es2015-arrow-functions {"node":"4"}
  transform-es2015-block-scoping {"node":"4"}
  transform-es2015-classes {"node":"4"}

  transform-es2015-destructuring {"node":"4"}
  transform-es2015-for-of {"node":"4"}
  transform-es2015-function-name {"node":"4"}
  transform-es2015-object-super {"node":"4"}
  transform-es2015-parameters {"node":"4"}
  transform-es2015-spread {"node":"4"}
  transform-es2015-sticky-regex {"node":"4"}
  transform-es2015-unicode-regex {"node":"4"}
  transform-regenerator {"node":"4"}
  transform-exponentiation-operator {"node":"4"}
  transform-async-to-generator {"node":"4"}
  syntax-trailing-function-commas {"node":"4"}
```

Error: 
```
    TypeError: doNotCopy.includes is not a function
      
      at TypeMapper.convertOutputFieldConfig (src/typeMapper.js:291:170)
      at src/typeMapper.js:306:56
      at Array.forEach (native)
      at TypeMapper.convertOutputFieldConfigMap (src/typeMapper.js:305:34)
      at TypeComposer.setFields (src/typeComposer.js:112:126)
      at TypeComposer.addFields (src/typeComposer.js:157:12)
      at Object.<anonymous> (src/__mocks__/gqc.js:6:27)
      at Object.<anonymous> (src/__tests__/resolver-test.js:15:12)
```

Failing build: https://travis-ci.org/nodkz/graphql-compose/jobs/239600504
Source code: https://github.com/nodkz/graphql-compose/tree/0b6ba54cd89f3698528d7eb19d0f90c394812ca6

**Comment by existentialism** [comment]
@nodkz you will need to use the `useBuiltIns` option along with importing `babel-polyfill` so the babel plugin can rewrite that to only import the polyfills your targets need.

**Comment by nodkz** [comment]
@existentialism thanks for fast reply.
I'm currently playing with it. Debug shows that it use additional polyfills. But it does not insert polyfills... 
Questions:
- `graphql-compose` is a package/library. Can I safely use polyfills? Or it should be some runtime transforms?
- Should I use `import "babel-polyfill";` in every file? Khm, but how i know for the library it is not good to pollute globals.

PS. My previous babel config: https://github.com/nodkz/graphql-compose/blob/32a299d830baf05d2d44f0f742a300b57332a082/.babelrc

Thanks for the upcoming advice. 😉

**Comment by nodkz** [comment]
For further googlers my current solution is:
```js
{
  "plugins": [
    "transform-object-rest-spread",
    "transform-flow-strip-types",
    ["transform-runtime", { "polyfill": false }]
  ],
  "presets": [
    ["env", {
      "targets": {
        "node": 4
      },
    }]
  ],
}
```

You should not use polyfills for libraries/packages. It's not good if you pollute globals and native objects. `useBuiltIns: true` is not for libraries.  

**Also you need to replace `arr.includes()` by `arr.indexOf() > -1`. **

How I understood Babel can not determine types of variables. So babel does not know that `arr` is array type and can not safely replace `includes()` on some another es5 code. Cause you may have your own object/class with `includes` method and it should not be transpilled.
