### ISSUE TITLE
Using `targets: {"node": "current"}` does not work correctly for node "v7.10.x"

### ISSUE THREAD

**Issue by shanewholloway** [babel/babel-preset-env#320]
Running Node v7.10.0 with `targets: {"node": "current"}` option for babel-preset-env interprets the version as `7.1`.  The result is that "transform-async-to-generator" is included when it should not be, since v7.10 > v7.6.

**Comment by existentialism** [comment]
@shanewholloway thanks for the issue! we've actually [already implemented this](https://github.com/babel/babel-preset-env/pull/231) in the soon to be released 2.x version. (Also ref: https://github.com/babel/babel-preset-env/issues/187, https://github.com/babel/babel-preset-env/issues/261)

**Comment by shanewholloway** [comment]
Apologies! Apparently my search of your issue database was wrong.

**Comment by existentialism** [comment]
@shanewholloway no need to apologize, we'll try and get an updated version out w/ string version support asap!
