### ISSUE TITLE
Use Browserslist 2

### ISSUE THREAD

**Issue by ai** [babel/babel-preset-env#325]
We released Browserslist 2 with ([full changelog with our reasons](https://evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released)):

1. Better performance because of caching
2. It depends on `caniuse-lite` (1 MB) instead of `caniuse-db` (7 MB)
3. Now `last n versions` contains all browsers

Unfortunately, this changes requires major update for this tool too. But all this changes are important and will not have problems for most of users. As people told on conferences — don’t afraid major releases, just make changes smaller — it is best example.

We already released Autoprefixer 7 and doiuse 3 with new Browserslist. It is important for community to have same Browserslist version (especially because of different `last n versions` behaviour).

I understand that you will be able to update Browserslist only in next major (together with correct Browserslist usage).

**Comment by existentialism** [comment]
@ai we actually landed it in https://github.com/babel/babel-preset-env/pull/319, since we actually have a filter: https://github.com/babel/babel-preset-env/blob/master/src/index.js#L49. Going to land a few other 2.x backports and ship a 1.5 asap!

**Comment by existentialism** [comment]
Released [v1.5](https://github.com/babel/babel-preset-env/releases/tag/v1.5.0) which has browserslist 2!
