### ISSUE TITLE
targets.node should support "6.10"

### ISSUE THREAD

**Issue by Kosta-Github** [babel/babel-preset-env#336]
right now `targets.node` just supports a `number` but this leads to ambiguities with respect to `6.1` vs. `6.10`; `targets.node` should also support version `strings` like `"6.10"` ...

**Comment by Kosta-Github** [comment]
`"6.10"` seems to work but the docs about `targets.node` (mentioning only these allowed values `number | "current" | true` and also `parseFloat(process.versions.node)`) should be updated accordingly...

**Comment by yavorsky** [comment]
@Kosta-Github Thanks for the issue! Will be fixed soon.
