### ISSUE TITLE
please integrate with "transform-runtime"

### ISSUE THREAD

**Issue by dalimian** [babel/babel-preset-env#338]
one problem with global polyfills is that it might have lot more things than needed by our app.

transform-runtime addresses this by allowing to include **only** the polyfills if are used by bundle. but it does not know about babel-preset-env, would be great if these two plugins were combined somehow to be able to say something like - include only the polyfills that are used by my bundle and within those only the ones that meet the conditions of babel-preset-env.

**Comment by existentialism** [comment]
@dalimian thanks for the issue, going to consolidate this with https://github.com/babel/babel-preset-env/issues/246!

**Comment by dalimian** [comment]
thanks for quick feedback
