### ISSUE TITLE
Babel ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by fega** [babel/babel-preset-env#340]
Hello! I'm using:
```
"babel-cli": "^6.24.1",
 "babel-preset-env": "^1.5.1",
```
with async await, I'm not using a config file. but I'm getting:
```
module.exports = _asyncToGenerator(regeneratorRuntime.mark(function _callee() {
                                   ^
ReferenceError: regeneratorRuntime is not defined
```
Is this an error? or how can I solve that?

thanks

**Comment by hzoo** [comment]
You need to add the `regeneratorRuntime` module https://www.npmjs.com/package/regenerator-runtime.

It's included with `babel-polyfill` https://babeljs.io/docs/usage/polyfill/ if you want to use that, or in combination with https://github.com/babel/babel-preset-env#usebuiltins.

**Comment by Ma63d** [comment]
Hi! @hzoo.
I'm running Node v7.10.0 with targets: {"node": "current"} option, like this:
```javascript
require("babel-core/register")({
    "presets": [
        ["env", {
            "targets": {
                "node": "current" // or '7.10.0'
            }
        }]
    ]
});
require('./app')
```
and I 'm getting  ```ReferenceError: regeneratorRuntime is not defined ``` too. As Node v7.10.0 has already supported async/ await. Why it still reports that i should use `babel-polyfill` and enable `"regenerator": true` ?  Is there anything wrong with my config option? 

Thx!

**Comment by Akkuma** [comment]
@hzoo I have the same problem as @Ma63d essentially

```
  "babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "node": "current"
          }
        }
      ]
    ],
    "plugins": [
      "syntax-async-functions",
      [
        "transform-async-to-module-method",
        {
          "module": "creed",
          "method": "coroutine"
        }
      ]
    ],
    "sourceMaps": "inline"
```
regeneratorRuntime should not be required for any version of node I run in and I'm running this in 8.1.2

**Comment by codepunkt** [comment]
@Ma63d found a solution to your problem? running into the same problem now.

**Comment by rclai** [comment]
Don't know if this belongs in this issue but I'm running Node 8.6 and I was surprised to get this `regeneratorRuntime is not defined` error, since async/await should work in Node 8. I'm guessing there's something about babel-preset-env that's causing this?

I'm on `babel-core` 6.26 and `babel-preset-env` 1.6.0

My `.babelrc` is just
```
{
  "presets": ["env"]
}
```

Am I missing something?

**Comment by pho3nixf1re** [comment]
This was closed but it is clearly a bug in babel-preset-env. When using the node environment it should not transform async functions. Is there a workaround here or is there a fix in the pipeline?

**Comment by existentialism** [comment]
> This was closed but it is clearly a bug in babel-preset-env. 

@pho3nixf1re will need more information about your setup (babelrc, etc) or a small repo that reproduces the issue.

**Comment by hzoo** [comment]
>  When using the node environment it should not transform async functions.

@pho3nixf1re it's not clearly a bug, it depends on which node environment you are using. If you are using node 7/8 then yes it isn't necessary (the first post didn't give enough information and the comment ^ didn't specify the target). Again you need to provide a reproducible example for us to understand the issue.
