### ISSUE TITLE
babel-env chose wrong targets?

### ISSUE THREAD

**Issue by OlegLustenko** [babel/babel-preset-env#345]
Hi. If I understand the documentation correctly, I have an issue.

> ## targets.browsers
> Array<string> | string
> A query to select browsers (ex: last 2 versions, > 5%) using browserslist.
> Note, browsers' **results are overridden** by explicit items from targets.

I provide minimal example in [repo](https://github.com/OlegLustenko/babel_env_issue)
![](https://image.prntscr.com/image/934f8a2d9a514da5b6ce397e8c839315.png)

I expect, there will be ie 11, but not ie 10. Have I missed something?

**Comment by OlegLustenko** [comment]
Generally, if it's a bug I can fix it and make a PR

**Comment by existentialism** [comment]
@OlegLustenko nice catch! I pushed a PR before actually reading your comment... thanks for the PR offer, mind reviewing https://github.com/babel/babel-preset-env/issues/346?

**Comment by existentialism** [comment]
@OlegLustenko released in 1.5.2, thanks again for the report!
