### ISSUE TITLE
Error: Couldn't find preset "env" relative to directory "config"

### ISSUE THREAD

**Issue by megamindbrian** [babel/babel-preset-env#348]
Using WebStorm with a .babelrc set to es2015 and Angular 4 stack.  Any ideas why it is looking in the config folder instead of going up one folder where node_modules is installed?

**Comment by jaydenseric** [comment]
Are you certain your dev dependencies are installed when Babel is running, and that this package can be found in `node_modules`?

**Comment by pailoro** [comment]
+1
