### ISSUE TITLE
publish the collected and processed compat-table data on npm (new package)

### ISSUE THREAD

**Issue by graingert** [babel/babel-preset-env#349]
the babel-preset-env team have put a good deal of work into collecting compat-table data and processing it into a usable format:

https://github.com/babel/babel-preset-env/blob/master/scripts/build-data.js

It would be help me greatly if this ready-processed data were available as a simple json npm package, so I would not need a build script or git dependencies.

**Comment by graingert** [comment]
obviously the data is available at `babel-preset-env/data/**` but that's not part of the public babel-preset-env api.

**Comment by yavorsky** [comment]
@graingert Hi! It's pretty nice idea and we have some discussion previously. https://github.com/babel/babel-preset-env/issues/117

Also, it would be awesome if compat-table will use this package too, so we will have the single source of truth.

And for now, you actually can use babel-preset-env data for your purposes by importing data directly.
[Like we are doing for standalone version](https://github.com/yavorsky/babel-preset-env-standalone/blob/master/src/index.js#L1).
