### ISSUE TITLE
for-await syntax on node 8.1.0

### ISSUE THREAD

**Issue by pldin601** [babel/babel-preset-env#355]
Node v8.1.0. When I try to transpile for-await loop using "node": "current" target, I get the same for-await loop as is, but node says:
```
  for await (const v of gen()) {
      ^^^^^

SyntaxError: Unexpected reserved word
```

But when I change target to "node": "7" it transpiles for-await loop correctly.

**Comment by existentialism** [comment]
@pldin601 what is your .babelrc look like?

ForAwait syntax needs `transform-async-generator-functions` (or stage 3 preset), so it seems strange that it would work by simply changing the node target?

I verified this locally with both "current" on 8.1 and targeting 7 and both fail w/o enabling the transform.

**Comment by pldin601** [comment]
My .babelrc:

```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "7"
      }
    }],
    "stage-0",
    "react",
    "flow"
  ],
  "plugins": [
    "transform-runtime",
    "transform-async-generator-functions",
    "transform-function-bind"
  ],
  "ignore": [
    "src/client",
    "node_modules"
  ]
}
```

**Comment by haraldrudell** [comment]
I can confirm this issue.
works for env, {target: {node: 7}}
does not work for env, {target: {node: 'current'}} (v8.4.0)

**Comment by haraldrudell** [comment]
There's troubles with transform-async-generator-functions in general

it sometimes behaves like process.exit(0) at the end of the for loop, like unhandled promise rejection used to do.
