### ISSUE TITLE
BUG: babel-preset-env v2.0.0-alpha.12

### ISSUE THREAD

**Issue by jmbelloteau** [babel/babel-preset-env#356]
Hi,

Just to let you know I've meet a BUG with`babel-preset-env  v2.0.0-alpha.12`

Using webpack when building assets I get this message:

`uglifyjs unexpected token: punc ())`

It seems that the preset send to `uglifyjs` is not correct.

For this test I use `package.json' with this code:

```json
"browserslist": [
    "> 1%",
    "last 2 versions"
  ],
```
 to tell babel-preset-env wich config to load.

On the other side, when using `babel-preset-env v1.5.2` I'm using `.babelrc` with this code:

```
{
  "presets": [
    [
      "env",
      {
        "targets": {
          "browsers": [
            "> 1%",
            "last 2 versions"
          ]
        }
      }
    ]
  ]
}
```

With this last configuration I don't get any error in webpack

**Comment by existentialism** [comment]
@jmbelloteau you will have to continue to use the same `targets.browsers` as in 1.x until https://github.com/babel/babel-preset-env/pull/161 lands.

**Comment by jmbelloteau** [comment]
@existentialism 'right! thank you 👍
