### ISSUE TITLE
Package.json engines as node target

### ISSUE THREAD

**Issue by k15a** [babel/babel-preset-env#358]
Hey,

I am currently creating a package boilerplate for me and would like to use the engines field from package.json as the target for this preset.

Currently, we have the "current" option which will use the current node version as the target. The problem with this is, that I might have installed the node version 8 but I want to support all versions down to version 4. When I compile the files with Babel to distribute them with NPM I would miss support for node versions which don't support all the language features my current node version supports.

As I would like to infer the targets.node option directly from the package.json engines field it would be great if this preset could support a similar structure.

**Comment by hzoo** [comment]
thanks for the issue, we have a pr to cover this already https://github.com/babel/babel-preset-env/pull/114 but not merged yet.

**Comment by existentialism** [comment]
Let's continue conversation in https://github.com/babel/babel-preset-env/pull/114 (will push an update to it today/asap?)
