### ISSUE TITLE
Uneeded polyfills / features on Node 8.1.2

### ISSUE THREAD

**Issue by tinovyatkin** [babel/babel-preset-env#361]
Debug outputs:

```
Using targets:
{
  "node": "8.1.2"
}

Modules transform: commonjs

Using plugins:
  syntax-trailing-function-commas {"node":"8.1.2"}

Using polyfills:
  es7.string.pad-start {"node":"8.1.2"}
  es7.string.pad-end {"node":"8.1.2"}
```

But all these features are supported natively on node 8.1.2 (node.green) - trailing commas as well as string paddings.

**Comment by hzoo** [comment]
we use compat-table for data so either we need to update that in package.json and rebuild or compat-table doesn't have the data yet etiher
