### ISSUE TITLE
Unneeded polyfills

### ISSUE THREAD

**Issue by pixelass** [babel/babel-preset-env#365]
Whenever I use `import 'babel-polyfill'` I get code like this: (**IE8**)

Not sure what I'm doing wrong here

```js 
// Thank's IE8 for his funny defineProperty
module.exports = !require(27)(function(){
  return Object.defineProperty({}, 'a', {get: function(){ return 7; }}).a != 7;
});
},{"27":27}],22:[function(require,module,exports){
var isObject = require(42)
  , document = require(31).document
  // in old IE typeof document.createElement is 'object'
  , is = isObject(document) && isObject(document.createElement);
module.exports = function(it){
  return is ? document.createElement(it) : {};
};
},{"31":31,"42":42}],23:[function(require,module,exports){
// IE 8- don't enum bug keys
```

```json
  "babel": {
    "presets": [
      "es2015",
      "stage-2",
      [
        "env",
        {
          "loose": true,
          "debug": true,
          "useBuiltIns": true,
          "targets": {
            "chrome": "57"
          }
        }
      ]
    ],
    "env": {
      "development": {
        "sourceMaps": "inline"
      }
    }
  }
```

```
Using targets:
{
  "chrome": "57"
}

Modules transform: commonjs

Using plugins:
  syntax-trailing-function-commas {"chrome":"57"}

Using polyfills:
  web.timers {"chrome":"57"}
  web.immediate {"chrome":"57"}
  web.dom.iterable {"chrome":"57"}
```

I tried several different configs (disable or enable builtIns, loose, etc)

I always end up with a 10000 line JS file full of unneeded polyfills

**Comment by yavorsky** [comment]
What bundler do you use? Can you share config?
for chrome 57, `preset-env` just replaces
`import 'babel-polyfill'` with
```
require('core-js/modules/web.timers');
require('core-js/modules/web.immediate');
require('core-js/modules/web.dom.iterable');
```
in your case.

Also, don't include es2015 preset if you already have preset-env. It includes all plugins from es2015/2016/2017 presets.

**Comment by pixelass** [comment]
I think the 2015 is still dirt from testing 20000 different configs 🤣

I just tested it with removing es2015.

Still getting this:

```js
// 7.2.1 RequireObjectCoercible(argument)
module.exports = function(it){
  if(it == undefined)throw TypeError("Can't call method on  " + it);
  return it;
};
},{}],21:[function(require,module,exports){
// Thank's IE8 for his funny defineProperty
```

This is the config: https://github.com/pixelass/paraglider/blob/master/package.json#L135-L151

I removed the `import 'abel-polyfill'` due to this issue and now use polyfill.io in the demos


In older versions I added transform-runtime because of this isse: https://github.com/pixelass/paraglider/blob/4d1720c7d0fd3d14b1a73f6f0891895f9e7632c9/package.json#L128-L136

**Comment by pixelass** [comment]
I removed it locally and tested it. I just didn't push the cahnges since it didn't result in the desired behavior

**Comment by pixelass** [comment]
I just pushed a test branch to show the issue

**package.json**  
https://github.com/pixelass/paraglider/blob/test/babel-preset-env/package.json#L131-L152  

**dist**  
https://github.com/pixelass/paraglider/blob/test/babel-preset-env/dist/paraglider.js#L568-L581

**testbranch**  
https://github.com/pixelass/paraglider/tree/test/babel-preset-env

**Comment by pixelass** [comment]
Here's the reason why I added es2015. It was as mentioned dirt from another test (the one with chrome 57)

I just ran a test for chrome 59 and got an error without the preset es2015

## Test chrome 59

### without es2015:

```

Using targets:
{
  "chrome": "59"
}

Modules transform: commonjs

Using plugins:

Using polyfills:
  web.timers {"chrome":"59"}
  web.immediate {"chrome":"59"}
  web.dom.iterable {"chrome":"59"}
errorify: SyntaxError: Unexpected token: name (Glider) while parsing file: /<WORKSPACE>paraglider/src/glider/index.js
```

### with es2015

```
babel-preset-env: `DEBUG` option

Using targets:
{
  "chrome": "59"
}

Modules transform: commonjs

Using plugins:

Using polyfills:
  web.timers {"chrome":"59"}
  web.immediate {"chrome":"59"}
  web.dom.iterable {"chrome":"59"}
```

**Comment by pixelass** [comment]
That seems to have been the uglify, so I removed it for testing purposes.

The issue still remains, no matter what I try

**package.json**  
https://github.com/pixelass/paraglider/blob/test/babel-preset-env-chrome-59/package.json#L127-L137  

**dist**  
https://github.com/pixelass/paraglider/blob/test/babel-preset-env-chrome-59/dist/paraglider.js#L79-L92

**Comment by pixelass** [comment]
I'm really frustrated with this. It has cost me sevreal days of useless testing and I will now remove this all together.

Keeping this open for reference but I'm removing it from all my open source packages since it makes no sense to invest any more time to this issue.

**Comment by yavorsky** [comment]
@pixelass I'll try to repoduce this with https://github.com/pixelass/paraglider in a few hours.

**Comment by pixelass** [comment]
@yavorsky thx. I'm currently removing the entire polyfill logic and will suggest polyfill.io instead. It seems to work out of the box and reduces the filesize of my library. I am only adding polyfills in the dist and demo versions so I will deliver dist without polyfills and the demo now uses polyfill.io

I actually abused this project to test babel-preset-env which I should not have done. It all looked so easy on television. 🤡

I also tried transpiling with babel

transpiled: 

```js
require('core-js/modules/web.timers');

require('core-js/modules/web.immediate');

require('core-js/modules/web.dom.iterable');
```

generated: 

```js
};
},{}],32:[function(require,module,exports){
// Thank's IE8 for his funny defineProperty
module.exports = !require(38)(function(){
  return Object.defineProperty({}, 'a', {get: function(){ return 7; }}).a != 7;
});
},{"38":38}],33:[function(require,module,exports){
var isObject = require(53)
  , document = require(42).document
  // in old IE typeof document.createElement is 'object'
  , is = isObject(document) && isObject(document.createElement);
module.exports = function(it){
  return is ? document.createElement(it) : {};
};
},{"42":42,"53":53}],34:[function(require,module,exports){
// IE 8- don't enum bug keys
```

**Comment by milesj** [comment]
Is that the only IE8-ish code in the output? Perhaps that code is required regardless of browser version?

**Comment by pixelass** [comment]
I'm not sure about it being needed. I had a similar thought. That's why I checked so many options. 
That would mean that the following imports would generate 5k loc which I highly doubt.

```js
require('core-js/modules/web.timers');
require('core-js/modules/web.immediate');
require('core-js/modules/web.dom.iterable');
```

**Comment by yavorsky** [comment]
Oh, the only redundant polyfills is **web.timers**, **web.immediate** and **web.dom.iterable**? Right?

Currently we including it regardless of the config because there is no way to know about where this polyfills is supported. (by checking it manually - currently nowhere). It could be disabled by adding them to [excludes](https://github.com/babel/babel-preset-env#exclude) option.

**Comment by pixelass** [comment]
why is this closed without ever being resolved?

**Comment by yavorsky** [comment]
@pixelass Sorry, but you haven't answered on the last comment, I thought it resolved the issue.

**Comment by zloirock** [comment]
> Thank's IE8 for his funny defineProperty
> ...
> in old IE typeof document.createElement is 'object'
> ...
> IE 8- don't enum bug keys
> ...
> etc

That's comments in internal `core-js` helpers. Solutions like `babel-preset-env` can't save us from this. We can add alternative versions of those helpers for modern environments, but we should add alternative versions of modules which use those helpers, alternative entry points - it's tens of thousands of new files, but `core-js` already is too bloated. I have some ideas how to partially solve this problem, but definitely not soon.

> `core-js/modules/web.timers`

I don't know why `babel-preset-env` add it for modern environments - it's required only for IE9-.

**Comment by pixelass** [comment]
ok. thank you. that clarifies this.
