### ISSUE TITLE
Debug option reports unincluded stage-x polyfills

### ISSUE THREAD

**Issue by ClementParis016** [babel/babel-preset-env#369]
When using the `debug` option, the console output reports it's using polyfills for stage-x features, such as `
es7.string.pad-start` and `es7.string.pad-end` (currently stage-4) in the following capture:

![image](https://user-images.githubusercontent.com/5601687/27843462-0a01aa3c-6114-11e7-89a6-b7a676bd4bd6.png)

This is a bit confusing since stage-x polyfills aren't included in the output, as specified in the docs [here](https://github.com/babel/babel-preset-env#support-all-plugins-in-babel-that-are-considered-latest) and [here](https://github.com/babel/babel-preset-env#usebuiltins).

We could either don't log those polyfills at all or log additional information for them, stating that they're not going to be included in the output.

What do you think? I may be able to work on a PR if any of those solutions is satisfying.

**Comment by yavorsky** [comment]
@ClementParis016 Stage 4 contains of finished proposals which have 'Shipping' status. Look: https://tc39.github.io/process-document.

Babel don't have stage-4 preset, so all plugins is expected as a part of the specification and included in es2015/16/17.

Polyfills going the same way:
`es7.string.pad-start`/`es7.string.pad-end` is a part of ES2017 standart. You can found it in the official language specification: https://tc39.github.io/ecma262/#sec-string.prototype.padstart.

**Comment by ClementParis016** [comment]
@yavorsky I fully understand that those methods are part of ES7, but however if the target env for babel-preset-env doesn't support them natively they are reported in the "Using polyfills" section which is confusing because those polyfills aren't built with the bundle in the end.

Though, I'm not sure if my explanation is unclear or if I'm missing something, let me know if it makes sense to you.

**Comment by yavorsky** [comment]
@ClementParis016 Oh, I undrstand! Yeah, actually we completely change debug logic for polyfills and going to land it with 2.0 branch, so for polyfills with 'usage' option there will be logged only those polyfiils that was actually used.
Look:
https://github.com/babel/babel-preset-env/pull/310
https://github.com/babel/babel-preset-env/pull/291
https://github.com/babel/babel-preset-env/pull/241

**Comment by ClementParis016** [comment]
Perfect then, it looks good!
