### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by andreineculau** [babel/babel-preset-env#37]
Foreword: It's hard to summarize my thoughts via a handful of sparse "issues", so I'll try to be concise in a unicorn "issue" instead, pick your brain, and take it from there.

There's not just one babel-plugin that can provide support for a feature e.g. async/await has multiple implementation alternatives. On top of that, one might want to blacklist a plugin.

Given these two scenarios alone, I see a standalone package that has 1 concern alone: decide which features are needed for a specific environment. Another package can then have the concern to map a set of desired features to known plugins (the mapping should be allowed to be extended, the plugins should be prioritized, and the prioritization should be allowed to be extended).

At this stage, a babel-preset package could just hold a set of the required features, and use the other two packages to return the necessary babel plugins. The babel plugins themselves would not be dependencies, but peerDependencies at most, leaving the dependency resolution up to the caller so that we don't end up installing n dependencies, while only 1 is actually truly required.

Hope the above makes some sense. I like the base of this data-driven preset, but I'd like the rigid structure (strict set of plugins and download of maybe-redundant dependencies) to shed off.

**Comment by hzoo** [comment]
> On top of that, one might want to blacklist a plugin

I added a whitelist option if you have to compile. Not sure about blacklist since we are trying to be safe.

> maybe-redundant dependencies

Is is because of size/install time? Haven't had much experience with peerDependencies but if you have a better explanation of how that would work we can discuss. It's pretty early and the easiest thing to do was to include all plugins - it's a build tool and its good not to have to think about installing anything other than this.

**Comment by gajus** [comment]
> I added a whitelist option if you have to compile. Not sure about blacklist since we are trying to be safe.

As an example of a use case, I'd like to have one bundle for browsers that do not support generators  (using `transform-regenerator`) and one for that do support the generators.

I cannot see how to achieve this without a blacklist option.

**Comment by hzoo** [comment]
Workaround is using the env option to have multiple env presets?

```js
{
  "env": {
    "support-generators": {
      "presets": [
        ["env", {
          "targets": {
            "chrome": 54
          }
        }]
      ]
    },
    "no-generators": {
      "presets": [
        ["env", {
          "targets": {
            "ie": 9
          }
        }]
      ]
    }
  }
}
```

but yeah we could probably add that

**Comment by hzoo** [comment]
I think we can come back to some of these later. There is an issue now for blacklist which we can add soon. https://github.com/babel/babel-preset-env/issues/60
