### ISSUE TITLE
Language spec targets instead of versions of browsers/Node.js

### ISSUE THREAD

**Issue by rtsao** [babel/babel-preset-env#373]
I'd love for the ability to do something like this:

```
{
  "presets": [
    "env", {
      "targets": {
        "languageSpecification": "ES2016"
      },
    }
  ] 
}
```

You might say this doesn't make sense, but this preset includes things beyond just `babel-preset-es2015`, so being able to use language version would be nice as this preset evolves.

**Comment by XaveScor** [comment]
Why? Your target is browser or Nodejs. Not some standard.

**Comment by rtsao** [comment]
Not if you're publishing a universal JS library. You don't know what the consuming browser/runtime is – you just make an arbitrary decision as to what JS spec your published module conforms to.

**Comment by XaveScor** [comment]
I know the minimal browser/node version. I rely that the browser/node developer save the backward compatibility.
Ok, let's imagine we decide your proposal. Let's look ES5 support. http://kangax.github.io/compat-table/es5/ I want to support IE11 and Safari. What I need to do?
Your proposal is tangle for developers. After we need to look how browsers support every feature. Why? We can do that in the babel side.

**Comment by milesj** [comment]
@rtsao So publish the source code alongside the compiled code and give the consumer the ability to compile the source code down themselves using their own build process and configuration.

**Comment by rtsao** [comment]
> So publish the source code alongside the compiled code and give the consumer the ability to compile the source code down themselves using their own build process and configuration.

Personally, I think this approach is unscalable and shifts too much burden to downstream consumers of packages. For example, if I'm authoring my JS package in a language other than JavaScript, merely providing the source code may not be very helpful. It's common for package authors to employ highly complex, specialized code transformations and build steps (arbitrary syntax/macros, cross-compilation from other languages, etc). Requiring the consumer configure/control this process is probably not going to be a good experience even if a convention could be established.

> The community needs to start heading that direction instead of compiling down to ES3 or assuming what target they need.

I don't see why there needs to be any assumptions at all. Couldn't package authors simply elect to provide their package in a variety formats (corresponding to JS language specifications)? It'd always be their choice, and providing in multiple formats could be optional. Integrating this into `babel-preset-env` would make this process very easy for package authors. As a package author, I'd merely specify the output language targets I care to support and be done with it. There's already a well-established concept of package.json fields (implemented in [enhanced-resolve](https://github.com/webpack/enhanced-resolve)) dictating which version a module bundler will consume (i.e. the `browser` field). Something similar could be done for language specs, and it'd be purely progressive enhancement as well.

**Comment by rtsao** [comment]
Getting back to the original issue, I don't see a need to create an interface for this as long as the underlying plugin data is easily accessible. I've created a PR that resolves this issue by doing just that: https://github.com/babel/babel-preset-env/pull/376
