### ISSUE TITLE
Couldn't Find Plugins

### ISSUE THREAD

**Issue by okonomiyaki3000** [babel/babel-preset-env#374]
When installing `babel-preset-env`, many additional plugins are installed as dependencies (for example: `babel-plugin-check-es2015-constants`). When running, any required plugins get loaded like `require(--plugin-name--);`.  OK, you already knew that.

So, in the plugin module's `package.json`, there is a "main" property which, invariably, is `lib/index.js`. That tells `require()` which file to actually load. Right, this is not new information.

The problem now is that (for some reason...), when these dependencies are installed, their `package.json` files are modified in some complex ways and the "main" property is gone. So now, they can't be loaded in the normal way. 

Why this happening? Also, why is this only happening to me?

**Comment by okonomiyaki3000** [comment]
Update: uninstalling `babel-preset-env` and reinstalling it with yarn instead of npm fixed the issue. So NPM is dumb? Or I am?

**Comment by yavorsky** [comment]
@okonomiyaki3000 What npm version do you use?

**Comment by okonomiyaki3000** [comment]
While trying to get this to work, I updated to 5.3 to see if it would help. I might have had 5.0 before that, I don't remember. I only ran `npm install bable-preset-env`, the dependencies were installed automatically.

**Comment by existentialism** [comment]
@okonomiyaki3000 closing for now, let us know if you run into any more trouble!
