### ISSUE TITLE
Can't use decorators with "targets": { "node": 7 }

### ISSUE THREAD

**Issue by elsueno** [babel/babel-preset-env#377]
Hi there!

I want to use decorators with node 7 (electron) but I'm always getting "SyntaxError: Method has decorators, put the decorator plugin before the classes one."
I've tried transform-decorators-legacy and [preset-decorators-legacy](https://github.com/kt3k/babel-preset-decorators-legacy) and nothing seems to work.
This is the .babelrc I'm working with: https://github.com/chentsulin/electron-react-boilerplate/blob/master/.babelrc

Thanks!

**Comment by yavorsky** [comment]
Hi! babel-preset-env is supports all plugins [(es2015, 2016, 2017)](https://babeljs.io/docs/plugins/preset-latest/), but not stage plugins and any other external plugins. Just add `transform-decorators-legacy` to your `plugins` list.

**Comment by hzoo** [comment]
https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy#note-order-of-plugins-matters
