### ISSUE TITLE
Document compilation performance enhancements

### ISSUE THREAD

**Issue by ustun** [babel/babel-preset-env#38]
I am assuming that usage of this plugin during development when one targets say the locally installed Chrome that is latest, will bypass most of the conversions Babel does. 

The question then is how much of a speedup does this cause during development. (In fact, that's the path via which I found this lib, I was thinking if I could get babel to just compile the JSX bits in my react app, it would make things much faster for compilation.)

It would be nice to document these speedups so that if they are good enough, we can suggest people to use this especially development to minimize compilation times.

**Comment by hzoo** [comment]
How should we document the speedups? The numbers will change and each plugin/environment is different so not sure how. I think the idea itself is already that - babel will process less with less plugins and the resulting output code is less as well.

**Comment by chicoxyzzy** [comment]
@ustun in most cases good old ES5 code will be more performant than modern ES2015+ code because optimisation compilers and feature support in VM are separate things and almost all of ES2015+ can't be optimised right now.

**Comment by hzoo** [comment]
> It would be nice to document these speedups so that if they are good enough, we can suggest people to use this especially development to minimize compilation times.

This kind of thing will change a lot and by making this preset we are suggesting to use it in development/prod. I'm not sure the best way and it's kind of early so we can come back to this unless someone wants to start a benchmark kind of thing or has one in mind
