### ISSUE TITLE
Support ECMAScript versions as `targets`?

### ISSUE THREAD

**Issue by rauschma** [babel/babel-preset-env#381]
I’m not sure how much that would be used in practice, but for some experiments and tests, it would be nice if one could specify an ES version to target.

Examples:

```
"targets": { "ecmascript": "2015" }
"targets": { "ecmascript": "5" }
```

**Comment by chicoxyzzy** [comment]
There are `babel-preset-es*` presets for that. Also never know what does `"targets": { "ecmascript": "2017" }` mean. Should it also add `babel-preset-es2016`, `babel-preset-es2015`, etc. or does your environment already support ES2016 and ES2015 and needs just ES2017?

**Comment by rtsao** [comment]
> There are babel-preset-es* presets for that. 

IIRC these won't be created for future versions in favor of this preset. So for that reason I think supporting language targets make sense.

**Comment by AntJanus** [comment]
@chicoxyzzy I think if you specify `targets: { "ecmascript": "5" }`, you're compiling everything above it to the target. That's pretty straightforward. TypeScript does the same thing.

**Comment by xtuc** [comment]
This could be a good replacement for `babel-preset-es*`.

I think that { escmascript: es2016 } shoud include babel-preset-es2016, babel-preset-es2015.

I would prefer the es2015 format rather than the es6 one.

**Comment by chicoxyzzy** [comment]
Why should it include es2015 if that's not specified explicitly?

**Comment by rauschma** [comment]
My understanding would be:

* `{ "ecmascript": "5" }`: the browser supports only ES5 or older. Transpile any newer features to ES5.
    * Same as `babel-latest`.
* `{ "ecmascript": "2015" }`: the browser supports ES2015 or older. Transpile any newer features to ES6.
    * Roughly similar to including all `babel-preset-*` *except* `babel-preset-es2015` (which the browser already knows).
* Etc.

**Comment by AntJanus** [comment]
I think that makes the most sense. Like I said, it's what TypeScript does: you specify a compile target. A compile target of "ES5" means you're compiling down to ES5. ES2015 means you compile down to ES2015, etc.

**Comment by b-zee** [comment]
I think #234 and #264 are related.

In version 1 there is the `uglify` option, which will, according to the documentation, transpile down to **ES5**. Version 2 opts for a `forceAllTransforms`, which should do the same thing. However, those options don't directly make it clear it's about transpiling it to **ES5**.

Your solution seems the ultimate solution and is unambiguous in what result it would yield. Just like TypeScript (see [www.typescriptslang.org/...](https://www.typescriptlang.org/docs/handbook/compiler-options.html)) offers a `target` option, this package should too. See .
