### ISSUE TITLE
useBuiltins usage with experimental / stage-x built-ins

### ISSUE THREAD

**Issue by modosc** [babel/babel-preset-env#382]
> NOTE: This does not currently polyfill experimental/stage-x built-ins like the regular "babel-polyfill"

can you clarify this wording in the docs? i'm unsure if this means:

* using `babel-preset-stage-0` will cause me to needlessly pull in all of `babel-polyfill` even though `babel-preset-env` only pulled in a subset

or

* using `babel-preset-stage-0` may break because it could depend on a polyfill that's being removed by `babel-preset-env`

also, is there a way to determine which polyfills a given babel plugin is using?

**Comment by mrtnbroder** [comment]
I'd also like to know that, I'm not sure `babel-preset-env` works how I'd imagine it to work. This includes usage of any `state-x` preset.
