### ISSUE TITLE
Target browsers and Node

### ISSUE THREAD

**Issue by AntJanus** [babel/babel-preset-env#387]
I looked through the docs, and maybe this just needs to be a docs addition (I'm happy to contribute), but is there a way to specify both Node and Browser targets? I haven't tried it but here's an example: 

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"],
        "node": "current"
      }
    }]
  ]
}
```

I use Babel + Webpack for compiling the front-end and babel register for the back-end. I'm not sure what the current convention is for using `babel-preset-env` in this manner.

**Comment by hzoo** [comment]
You'd want to apply a different config for front end and backend right? You can use process.env to determine. If you combine them then it takes the least common denom

http://babeljs.io/docs/usage/babelrc/#env-option (yes its confusing that it's named env and this is "preset-env"

**Comment by benschenker** [comment]
Alternatively, add another .babelrc in the web/browser folder with settings specific to browsers, it will take precedence.
See: https://babeljs.io/docs/usage/babelrc/#lookup-behavior

**Comment by lerit** [comment]
i face the same problem.the targets setting is an object,and so set node and browsers in same babelrc file is legal.but only the last settting work.it ambiguous

**Comment by hzoo** [comment]
I wouldn't say it's ambiguous, it does the least common denominator of the options you chose otherwise it would fail against one of those options. Babel by default produces a 1 to 1 mapping of folder to folder, not 1 to many

**Comment by lerit** [comment]
ok,thanks,i will split it into two babelrc that one for front another for backend
