### ISSUE TITLE
Additionally compile specific node_modules

### ISSUE THREAD

**Issue by ianwremmel** [babel/babel-preset-env#388]
I'm not sure if this is a question or a feature request and i'm not sure if it belongs here or the babel repo. 

There seem to be a growing set of module authors moving to modern JavaScript syntax without considering the ramifications for projects that must function in active yet dated web browsers (specifically, IE 11). Some of these authors haven't considered there's a reason to run their projects in browsers and others don't care; one author told me to use tooling to build it for the target browser myself. 

I spent several hours playing with regexes and globs to try to figure out how to build my code as well as specific node modules before giving up and simply removing the offending library from my project and finding a different solution.

My ask is: can the babel-preset-env (or babel) docs (or possibly code) be updated to more helpfully explain how one would build one's own code and select node_modules when necessary?

**Comment by hzoo** [comment]
Yeah this isn't a feature since it just compiles what you tell it to, just docs for babel-loader or cli with ignore/only (which is pretty broken on babel 6.x)

**Comment by ianwremmel** [comment]
yea, that's kinda what i figured. is there somewhere more appropriate for me to open this issue? or is this a good enough spot?
