### ISSUE TITLE
How to import/export in Node with this?

### ISSUE THREAD

**Issue by corysimmons** [babel/babel-preset-env#395]
Had a workflow with babel-preset-es2015 and babel-preset-stage-0 but this project seems pretty cool. The only problem is `import` and `export` don't work when your target is just `"node": "current"`.

Is there a particular plugin I need to enable this feature? If so, it might be worth adding a mention in the docs (this was the only hiccup I had with this preset).

**Comment by flashYang** [comment]
you can try  {"targets": {"node": 7}}

**Comment by corysimmons** [comment]
I'm using Node 8.3.0 and have it set to `"node": "current"` which [should](https://github.com/babel/babel-preset-env#support-a-target-option-node-current-to-compile-for-the-currently-running-node-version) target my env's node version.

**Comment by flashYang** [comment]
you can try this demo
https://github.com/thinkjones/GeneConroyJonesArticles/tree/master/babel_quickstart

**Comment by flashYang** [comment]
the demo, I have try, working
https://github.com/thinkjones/GeneConroyJonesArticles/tree/master/babel_quickstart

**Comment by existentialism** [comment]
> The only problem is import and export don't work when your target is just "node": "current"

Can you elaborate? What is your .babelrc? Any chance for a small repo that repros the issue?

This preset supports the same `module` option as the es2015 preset.

**Comment by corysimmons** [comment]
I'm functional. Holy crap. I forgot my babel config on my example... it totally works. So sorry for wasting everyone's time. X_X

**Comment by existentialism** [comment]
@corysimmons no worries, glad it works!

**Comment by corysimmons** [comment]
Me too, excited to minimize my Babel pipelines. 😺
