### ISSUE TITLE
Ensure the distributed bundle works in Node 0.10

### ISSUE THREAD

**Issue by baer** [babel/babel-preset-env#4]
Currently the transpile targets Node 4+. Once features have stabilized we should expand that support to 0.10

**Comment by hzoo** [comment]
We run the es2015 preset now + travis so this is fixed

**Comment by hzoo** [comment]
Issue migrated to babel/babel#6393

**Comment by hzoo** [comment]
testing!

**Comment by hzoo** [comment]
Issue migrated to babel/babel#6394

**Comment by hzoo** [comment]
Closed Issue migrated to babel/babel#6395
