### ISSUE TITLE
mixed-order import-exports

### ISSUE THREAD

**Issue by mechanical-turk** [babel/babel-preset-env#403]
My project dependencies can only be satisfied if certain modules are imported in a specific linear order. If that order is not satisfied, then my project doesn't load properly.

The problem I'm having with babel-preset env is that it transpiles module imports in what seems to be an arbitrary order (although I'm sure that this is intentional and serves another purpose).

Let me give an example:

Before babel:

```
import './reducer';
export * from './hocs';
```

After babel:

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _hocs = require('./hocs');

Object.keys(_hocs).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _hocs[key];
    }
  });
});

require('./reducer');
```

As you can see, although the require('/reducer') part should come first, it comes at the very end. Is this something I can modify with a setting, or am I doing something else wrong?

Thanks

**Comment by loganfsmyth** [comment]
Sounds like another example of https://github.com/babel/babel/issues/4356 potentially?

**Comment by mechanical-turk** [comment]
Yes @loganfsmyth, looks like it is. I'll close the issue, although it doesn't seem to be solved just yet.
