### ISSUE TITLE
Block scope transform not included when targeting Safari 10

### ISSUE THREAD

**Issue by ssilve1989** [babel/babel-preset-env#411]
Specifying a target of `"safari >= 10"` doesn't use the `transform-es2015-block-scoping` plugin. Yet Safari 10 does need this because of [this](https://bugs.webkit.org/show_bug.cgi?id=159270) bug.

Ex:
```javascript
{
  let a = 3
}

let a = 3
``` 
is an error in Safari 10.1.2 resulting in `SyntaxError: Can't create duplicate variable that shadows a global property: 'a'`.

I've had to manually include this plugin in the `include` option to get Safari working.

**Comment by existentialism** [comment]
@ssilve1989 thanks for the report! since we source our mappings via [compat-table](https://github.com/kangax/compat-table), mind reporting this over there?

**Comment by ssilve1989** [comment]
@existentialism done
