### ISSUE TITLE
Excluding a target

### ISSUE THREAD

**Issue by ro-savage** [babel/babel-preset-env#415]
I am sure I must be missing something, but I don't believe the documentation is clear.

I would like to exclude IE and Android. However, I can not see how to exclude them.

If I am using
`targets: {'browsers': ['last 2 versions'] }`

Can I then exclude IE somehow? Or do I need to individually target safari, chrome, firefox, edge, and_chr, etc and just leave out IE?

**Comment by hzoo** [comment]
This syntax is from https://github.com/ai/browserslist, we don't do any further processing other than merging so I would check that

**Comment by ro-savage** [comment]
@hzoo 

```js
    'targets': {
      'browsers': ['last 2 version'],
      'chrome': '50.0.0'
    },
```

Will overwrite the chrome from browserlist.

What about supporting

```js
    'targets': {
      'browsers': ['last 2 version'],
      'chrome': false
    },
```

to exclude a browser?

**Comment by Zephir77167** [comment]
Hey. Browserslist supports this:

```
targets: {
  browsers: [
    'last 2 versions',
    'not ie > 0',
    'not chrome > 0',
  ],
},
```
