### ISSUE TITLE
Support `browserslist` files

### ISSUE THREAD

**Issue by Kovensky** [babel/babel-preset-env#42]
Support loading the `browsers` data from a `browserslist` file, resolved the same way `.babelrc` is.

`browserslist.readConfig(pathToFile)` should DTRT (or return `false`).

**Comment by hzoo** [comment]
https://github.com/babel/babel-preset-env/issues/26 should cover this

**Comment by Kovensky** [comment]
Indeed it does :D

**Comment by hzoo** [comment]
and https://github.com/babel/babel-preset-env/issues/34 - I guess we really want this feature 😄
