### ISSUE TITLE
Add support for Samsung Internet browser

### ISSUE THREAD

**Issue by philipwalton** [babel/babel-preset-env#428]
Samsumg Internet uses Chromium under the hood, but it doesn't always stay up-to-date with the latest version. We discovered this recently due to a bug report from a Samsung Internet user.

To fix it, we had to investigate the version of Chromium they use and [then manually add that to the browser list](https://github.com/GoogleChrome/workbox/pull/815/files#diff-7b9b61c220cc1842c38185dad092626bR162):

```js
const babelPlugin = babel({
  presets: [['env', {
    targets: {
      browsers: ['chrome >= 51'],
    },
    // ...
});
```

But this requires a bit or work on the user's side. Since browserlist support Samsung Internet, ideally we'd be able to do this:

```js
const babelPlugin = babel({
  presets: [['env', {
    targets: {
      browsers: ['last 2 Samsung versions'],
    },
    // ...
});
```

I haven't looked into whether this can be done solely on the `babel-preset-env` side, or if it would require changes to http://kangax.github.io/compat-table. If the latter is the case, maybe we can loop in @poshaughnessy for help making that happen?

**Comment by existentialism** [comment]
@philipwalton we could maybe create a mapping similar to [`electron-to-chromium`](https://github.com/kilian/electron-to-chromium) which powers our electron targets?

**Comment by philipwalton** [comment]
@existentialism seems like something like that could work well. I wonder if other browserlist consumers already have a solution in place to handle Samsung Internet.
