### ISSUE TITLE
Browserslist targets seemingly not working

### ISSUE THREAD

**Issue by Smolations** [babel/babel-preset-env#431]
I am not sure if this is a babel thing, a babel-preset-env thing, a babel-loader thing, or a browserlist thing, but I am at my wits end at the moment.

I am using the above babel libs, with the most recent released versions (what installs if you run `npm install <lib>` today) and I am seeing confusing results when I turn on debug info in my env options. I will also mention that I do not have the babel-polyfills lib specified in my `package.json` as I assumed I would no longer need it with the babel-preset-env lib. Here is my `.babelrc`:
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        // browserlist combined by OR clause
        // https://github.com/ai/browserslist
        "browsers": ["last 2 versions"],
      },
      "useBuiltIns": true,
      "debug": true,
    }],
  ],
  "plugins": [
    [
      "transform-es2015-modules-commonjs-simple", {
        "noMangle": true,
      },
    ],
  ],
}
```

When I run my webpack build, the debug info shows my target list as this:
```
Using targets:
{
  "chrome": "60",
  "android": "4.4.3",
  "edge": "14",
  "firefox": "54",
  "ie": "10",
  "ios": "10",
  "safari": "10"
}
```

Already strange as this seems to be a small subset of all browsers listed in the browserslist README, and also omits IE11. I didn't think anything of it until I ran into an IE11 bug regarding `Object.assign` (which I found strange since I see `es6.object.assign {"android":"4.4.3","ie":"10"}` in the debug output). If I have chosen the last two versions, why aren't there two versions listed for each browser? Is it because previous versions generally require more than later versions so it only shows the "least common denominator" in the targets debug output? I installed the browserslist lib locally and ran `$ browserslist "last 2 versions"` and it spit out everything as advertised, so I'm confused as to why my results are different:
```
$ browserslist "last 2 versions"
and_chr 61
and_ff 55
and_qq 1.2
and_uc 11.4
android 56
android 4.4.3-4.4.4
baidu 7.12
bb 10
bb 7
chrome 61
chrome 60
edge 15
edge 14
firefox 55
firefox 54
ie 11
ie 10
ie_mob 11
ie_mob 10
ios_saf 11
ios_saf 10.3
op_mini all
op_mob 37
op_mob 12.1
opera 47
opera 46
safari 11
safari 10.1
samsung 5
samsung 4
```

Back to the config...In the interest of investigation, I added `"ie 11"` to my browserslist array. Same result. Then I removed the `"last 2 versions"` entry and only IE11 was shown as a target, as I'd expect. So then I tried only `"last 2 ie versions"` but only IE10 showed up. This is very confusing.

So, is the problem here or elsewhere? If the latter, where would you suspect the problem is?

**Comment by existentialism** [comment]
Hey!

Couple things:

The `useBuiltIns` option of [true in 1.x](https://github.com/babel/babel-preset-env/tree/1.x#usebuiltins) and [`entry` in 2.x](https://github.com/babel/babel-preset-env/#usebuiltins-entry) actually transforms your `import 'babel-polyfill'` statement into only the individual polyfills needed for your target environments. So, you still need to use `babel-polyfill`, otherwise no polyfills will be loaded :)

The debug output shows the lowest version of the target that caused a particular transform or polyfill to be added.

Sidenote, not really familiar with `transform-es2015-modules-commonjs-simple` but preset-env uses `transform-es2015-modules-commonjs`, so I'm not sure how well they play with each other.

**Comment by Smolations** [comment]
@existentialism Thank you! I was so baffled because no one seemed to be having the same issue when I was googling! Maybe my googling skills were lacking or I just didn't read the docs well enough.

I also took your advice and replaced my modules-commonjs plugin with the included one you recommended (the former wasn't included based on my config, so I don't know if they conflict) and everything compiled fine. Thanks for the quick response!

**Comment by existentialism** [comment]
@Smolations anytime!
