### ISSUE TITLE
Import instead of require for es6.promise 

### ISSUE THREAD

**Issue by sheerun** [babel/babel-preset-env#433]
I use both babel and babel-preset-env beta.2.

My .babelrc:

```
{
  "presets": [
    ["env", {
      "target": {
        "node": "4"
      },
      "useBuiltIns": "usage",
      "debug": true
    }]
  ]
}
```

Resulting start of compiled .js file:

```
#!/usr/bin/env node
"use strict";

import "babel-polyfill/lib/core-js/modules/es6.promise";

require("babel-polyfill/lib/core-js/modules/es6.symbol");

require("babel-polyfill/lib/core-js/modules/web.dom.iterable");

require("babel-polyfill/lib/regenerator-runtime/runtime");

require("babel-polyfill/lib/core-js/modules/es6.string.starts-with");
```

I suspect this might be because regenerator-runtime is added? But really, I have no idea.

**Comment by sheerun** [comment]
Here's minimal .js file to reproduce this issue:

```
const { startsWith } = require('lodash')
async function main () { }
```

it seems that both async and destruction are needed to trigger this

**Comment by Andarist** [comment]
Seems like a bug, could you create a simple repository with the reproduced issue? It always help with looking into reported issues faster.

**Comment by sheerun** [comment]
Here you go.. https://github.com/sheerun/babel-bug-repro

**Comment by nicolo-ribaudo** [comment]
It is probably related to https://github.com/babel/babel/pull/6304

**Comment by loganfsmyth** [comment]
It may have been https://github.com/babel/babel/pull/6230, but the other one hasn't been released yet. That said, this definitely _should_ use the `babel-helper-module-imports` that was added in that PR, so I'd say we should wait on this until `beta.3` is released, then this can be updated to use that helper and we can publish a beta.3 of `preset-env`
