### ISSUE TITLE
Feature: Precompile dependencies based on their engines

### ISSUE THREAD

**Issue by sheerun** [babel/babel-preset-env#435]
If I target node 0.10 or 0.12 and some of my dependencies support node >= 4, I need to precompile all of them. Currently it takes too much time (even minutes) for babel to precompile all dependencies (i.e. without ignoring node_modules), but most of them don't need it anyway.

Couldn't babel-preset-env automatically discover the target to precompile to per-package based on engines field? And skip precompiling all together if target of dependency package satisfies target of root package (e.g. if root package has node >= 4, and dependency has node >= 4, then we don't need to recompile them, on the other hand dependency has node >= 8 and e.g. for async functions, then we need to compile it so root package can support node >= 4).

I guess this is superset of #114 but it also includes analysing engines fields of sub-folders and selectively ignoring compilation if not needed.

**Comment by Andarist** [comment]
This is strongly connected to the ongoing discussion [here](https://github.com/babel/babel/issues/6328).
