### ISSUE TITLE
includes function not work in dynamic param

### ISSUE THREAD

**Issue by hai3460377** [babel/babel-preset-env#440]
I use the babel-preset-env@next  
and set 
"presets": [
        [
            "env",
            {
                "targets": {
                    "browsers":  ["ie >=9"]
                },
                "useBuiltIns": "usage"
            }
        ]
    ]

when use the [].includes or "".includes like this:

function test(  param   ){
var otherObject=someFn.get();
     otherObject. includes (param);
}
test ("?")

in Ie it will throw an error  the object has no includes function

**Comment by yavorsky** [comment]
Seems like a bug:
https://deploy-preview-1415--babel.netlify.com/repl#?babili=false&browsers=ie%209&build=&builtIns=usage&code_lz=MYewdgzgLgBCUAsCmAnA8gIwFZOLAvDANoC6A3AFDzLra5QB0AlmMADYCuAJkhABQAHAIYohAWwCUlIA&debug=false&forceAllTransforms=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cenv&targets=&version=6.26.0&envVersion=2.0.0-beta.2

Thanks!
