### ISSUE TITLE
Issues and Babel monorepo

### ISSUE THREAD

**Issue by jrolfs** [babel/babel-preset-env#442]
Are there plans to migrate the issues from this repository to the main Babel repository? Should new issues be opened there?

**Comment by xtuc** [comment]
I believe there are plans to migrate this repository to Babel one ([see experimental directory](https://github.com/babel/babel/tree/master/experimental/babel-preset-env)).

You can open your issues here, we can ask our bot to move the around.

I'm closing this for now, feel free to open it if needed.

**Comment by jrolfs** [comment]
Cool, that's all I wanted to know. Thank you.
