### ISSUE TITLE
babel-preset-env not support the module.exports,what should i do?

### ISSUE THREAD

**Issue by Sailor20** [babel/babel-preset-env#444]
when i update babel-preset-es2015 to babel-preset-env, an error accoured!
![image](https://user-images.githubusercontent.com/24997729/31584176-e7644100-b16e-11e7-8962-8746900474b6.png)

this is my .babelrc
![image](https://user-images.githubusercontent.com/24997729/31584188-fbda4c42-b16e-11e7-988f-5198199ad025.png)

what should i do? thanks for first

**Comment by hzoo** [comment]
You shouldn't be using add-module-exports + webpack + modules: false, it's going to error?

**Comment by Sailor20** [comment]
@hzoo thanks very much!
