### ISSUE TITLE
debug/warn/error info should go to console.error

### ISSUE THREAD

**Issue by wmertens** [babel/babel-preset-env#447]
Right now debug info gets into my files when I redirect output for processing. All notices from applications that are not actual output should be done via stderr, and therefore debug should use `console.error`.

**Comment by xtuc** [comment]
Yes, that's right.

Would you mind making a PR for this? All the accesses to console.log seems to be in [debug.js](https://github.com/babel/babel-preset-env/blob/master/src/debug.js).

Do you know if that's going to impact other stuff? Maybe some users are relying on the debug info in stdout?
