### ISSUE TITLE
关于Openld与使用Op.RP

### ISSUE THREAD

**Issue by Asudhaishao** [babel/babel-preset-env#448]
系统的第一部分是身份验证，即如何通过 URI 来认证用户身份。目前的网站都是依靠用户名和密码来登录认证，这就意味着大家在每个网站都需要注册用户名和密码，即便你使用的是同样的密码。如果使用 OpenID （参见规范），你的网站地址（URI）就是你的用户名，而你的密码安全的存储在一个 OpenID 服务网站上（你可以自己建立一个 OpenID 服务网站，也可以选择一个可信任的 OpenID 服务网站来完成注册）。

OpenID 简介 OpenID 官方网站 http://openid.net 首页对 OpenID 的介绍如下： OpenID is a free and easy way to use a single digital identity across the Internet. With one OpenID you can login to all your favorite websites and forget about online paperwork! 其大概意思就是说： OpenID 是一个单一的、 免费的数字身份标识，使用它，你就可以登录你经常登录的网站。 OpenID 提高了互联网服务的用户体验。显而易见，就终端用户而言， OpenID 降低了用户管理多个网站帐号的烦恼，用户可以享受类似单点登录的体 验。 对于企业来说， OpenID 降低了用户帐号管理的成本。 对于应用开发者来说， OpenID 是一个开放的、去中心化的，免费的、以用户为中心的身份标识体 系。 Java 的一个优势是跨平台，大家都熟悉的那句话： Write Once ， Run Anywhere （一次编写， 到处运行） ， 同样， OpenId 的优势是： Register Once ， Use Anywhere （一处注册，到处使用）。 OpenId 是一个以用户为中心的数字身份识别框架，它具有开放、分散、 自由等特性。 OpenId 的创建是基于这样一个概念： 我们可以通过 URI （或者 URL 网址） 来识别一个网站。 同样， 我们也可以通过这样的方式来识别一个用户的身 份。 OpenId 系统的身份认证就是通过 URI 来认证用户身份。目前绝大 部分网站 都是通过用户名与密码来登录认证用户身份， 这就要求大家在每个你要使用的网 站上注册一个帐号。 如果使用 OpenId ， 你可以在一个提供 OpenId 的网站上注册 一个 OpenId ，以后你可以使用这个 OpenId 去登录支持 OpenId 的网站。这正是 一处注册，到处使用的体现。 二、 OpenID 相关术语 End User ：终端用户，使用 OP 与 RP 的服务

**Comment by xtuc** [comment]
Please re-create an issue (assuming that's actually one) in english.
