### ISSUE TITLE
iCloud可实现锁定🔒

### ISSUE THREAD

**Issue by Asudhaishao** [babel/babel-preset-env#449]
使用HTML代码。在HTML的<head>；部分必须提供以下标签：
<link rel="openid2.provider" href="http://openid.com/server/endpoint/url"/>
可选的，如果用户使用委派（delegation）（就是用户宣称拥有一个不存在于该OpenID服务器上的本地标识），则需要使用下面的标签：
<link rel="openid2.local_id" href="http://openid.com/server/endpoint/url"/>
例如，某人正在使用openidprovider.com这个OpenID服务器来验证他在另一个OpenID服务器usersite.com上的身份，那么其本地标识将使用类似user.openidprovider.com的形式。
这个“发现”的过程允许外部站点知道两件事，其中一件是外部站点如何与OpenID服务器进行通讯：
⒈OpenID提供者端点URL：OpenID提供者的最终URL（服务器URL）。
⒉认证协议版本： OpenID认证使用的协议版本。
作为可选的，如果用户使用委派，那么外部站点将需要知道：
⒈用户宣称的标识：此标识为用户宣称属于自己的。它是在登录过程中用户提供过的标识。
⒉本地标识（OP-Local Identifier）：用户在其OpenID服务器上拥有的本地标识。
Relying Party
⒋ Relying Party站点建立与OpenID服务器之间的关联（可选）
苹果手机若在#icloud#里捆绑#apple id#可实现定位和锁定手机就算刷机也不会被重新激活。

**Comment by xtuc** [comment]
I'm closing this for now, please re-create an issue (assuming that's actually one) in english.
