### ISSUE TITLE
npm WARN deprecated babel-preset-latest@6.24.1: We're super 😸  excited that you're

### ISSUE THREAD

**Issue by wzup** [babel/babel-preset-env#453]
Can you explain more clear what does that mean? How to deal with it?

> We moved babel-preset-env into the main Babel repo under a different folder

**Comment by nicolo-ribaudo** [comment]
We moved the preset to another repository, but you should still be able to `npm install babel-preset-env`

**Comment by frenzzy** [comment]
http://babeljs.io/env

**Comment by hzoo** [comment]
It just means we wanted to move this repo into the main babel repo so it's easier to manage but we are in transition of moving issues since that can be difficult with labels and everything.

You should be able to just switch out latest with env like in the link ^
