### ISSUE TITLE
Object Spread Transform Not Included

### ISSUE THREAD

**Issue by iansinnott** [babel/babel-preset-env#49]
I was trying to create a babel config for some dev work and just wanted the target recent Chrome. I'm using Webpack 2 and babel-loader as the build pipeline. The following config caused a compiler error:

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": "last 2 Chrome versions"
      },
      "modules": false,
      "loose": true
    }]
  ]
}
```

However, manually adding `babel-plugin-transform-object-rest-spread` fixed the errors.

```json
{
  "presets": [
    ["env", {
      "targets": {
        "browsers": "last 2 Chrome versions"
      },
      "modules": false,
      "loose": true
    }]
  ],
  "plugins": [
    ["transform-object-rest-spread", { "useBuiltIns": true }]
  ]
}
```

What is the expected behavior here? Is `babel-plugin-transform-object-rest-spread` meant to be added manually?

Might relate to #22.

**Comment by hzoo** [comment]
So in the other issue we decided not to include any stage features by default and leave that up to the stage-x presets. It's not a part of ecmascript yet so was thinking it should be opt in I'd that makes sense.

**Comment by iansinnott** [comment]
Sure, that make sense. Not a big lift to add it outside the env preset. Thanks for the quick response @hzoo.

**Comment by simonbuchan** [comment]
Should probably update the readme Caveats section, which is currently confusingly saying

>make sure the plugin is at v6.19.0.

**Comment by hzoo** [comment]
@simonbuchan What's confusing about it - it's saying object rest spread needs to be 6.19.0. If you think it could be clearer please send a PR 🙂!

**Comment by andykenward** [comment]
So I take it that for `babel-plugin-transform-object-rest-spread` the settings should be

`["transform-object-rest-spread", { "useBuiltIns": true }]`

If using with `babel-preset-env`?

**Comment by hzoo** [comment]
useBuiltIns means that it will use `Object.assign` so you would need a polyfill. Doesn't have to be related to env unless you mean using `useBuiltIns` in env as well + importing babel-polyfill

**Comment by andykenward** [comment]
Yeah sorry. I should've said in conjunction with babel-polyfill

```
"babel": {
    "babelrc": false,
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": [
              "last 2 versions",
              "ios_saf >= 8",
              "not IE <= 10",
              "chrome >= 49",
              "firefox >= 49",
              "> 1%"
            ]
          },
          "debug": false,
          "loose": true,
          "modules": false,
          "useBuiltIns": true
        }
      ],
      "react"
    ],
    "plugins": [
      ["transform-object-rest-spread",
        {
          "useBuiltIns": true
        }
      ],
      "transform-flow-strip-types"
    ],
```

**Comment by joshperry** [comment]
If you're targetting node >= [6.8.1](http://node.green/#rest-parameters)--which suppors these operators natively without flags--I highly recommend using the [rest-spread _syntax_ plugin](https://www.npmjs.com/package/babel-plugin-syntax-object-rest-spread) instead of the transform.

**Comment by josser** [comment]
Just a note, if you are using env preset with browsers:  { ie >= 11 }
it will not work with ["transform-object-rest-spread", { "useBuiltIns": true }] because useBuitins: true cause it to generate Object.assign() calls which are not supported in IE 11. 

So, if you are targeting ie 11 be sure to set useBuiltins to false.

**Comment by leidegre** [comment]
@josser sure, but for that, you use a polyfill, for example, a conditional include from a popular CDN to pull in the needed bits. No reason to let everyone else suffer for IE11's shortcomings.

**Comment by andykenward** [comment]
@josser I use this [`object-assign`](https://github.com/sindresorhus/object-assign)

Then add
```js
Object.assign = require('object-assign');
```

So you can keep `"useBuiltIns": true`
