### ISSUE TITLE
Jspm compatibility with static declaration of dependencies?

### ISSUE THREAD

**Issue by tiagocpontesp** [babel/babel-preset-env#52]
Consider https://github.com/systemjs/builder/issues/45#issuecomment-75429700

**Comment by hzoo** [comment]
Not sure I have enough context how this is for preset-env? Do you mean to ask about the modules transform instead?

**Comment by tiagocpontesp** [comment]
JSPM pushes the build process to the browser. The problem is with the dynamic requires(), because SystemJS imports are async in nature. I _think_ there are other ways to get over the issue, like having a JSPM/registry entry manually specifying all of the file's possible deps, but replacing the string interpolation with a static dependency map seems to me like the best move overall.

**Comment by tiagocpontesp** [comment]
I'm guessing this is the foremost way to configure babel atm, so it maybe worth asking @guybedford's opinion.

**Comment by tiagocpontesp** [comment]
I think this comment explains it best: https://github.com/svg/svgo/issues/504#issuecomment-187732265

**Comment by loganfsmyth** [comment]
So you're asking that the `require` here: https://github.com/babel/babel-preset-env/blob/d489c2e0cbf6512f30e268da86c0ee816416018d/src/index.js#L169 be changes so that each require has the fully qualified statically analysable name. Right?

**Comment by tiagocpontesp** [comment]
Precisely

**Comment by guybedford** [comment]
It's probably advisable not to try run this through jspm as it isn't universal code made to run in the browser. In jspm you can still load a NodeJS modules normally with `import x from '@node/babel-preset-env'` which will then do a standard node_modules load, which should allow configuration with the jspm babel plugin fine.

**Comment by tiagocpontesp** [comment]
Thanks for your feedback. Excuse my misunderstandings.
