### ISSUE TITLE
import of `regenerator-runtime` is incorrect and UglifyJs issue

### ISSUE THREAD

**Issue by andykenward** [babel/babel-preset-env#67]
Using `v1.0.0` and `import 'babel-polyfill';`
I get this error when building my project.
```
ERROR in ./app/app.js
Module not found: Error: Can't resolve 'core-js/modules/regenerator-runtime/runtime' in '/Users/andykenward/Documents/_github/bob/app'
 @ ./app/app.js 46:0-53
 @ multi main

ERROR in main.5954769afe0c86762c19.js from UglifyJs
SyntaxError: Unexpected token punc «}», expected punc «:» [main.5954769afe0c86762c19.js:560,18]

```

shouldnt the import be
```
import "regenerator-runtime/runtime"
```

I thought it may have been a `yarn` over `npm`. So tried install dependency both ways but no change

```
  "engines": {
    "node": "6.9.1",
    "npm": "3.10.8",
    "yarn": "0.17.10"
  },
```
here is my babel config
```
"babel": {
    "babelrc": false,
    "presets": [
      [
        "env",
        {
          "targets": {
            "browsers": [
              "last 2 versions",
              "not ios_saf <= 8",
              "not IE <= 11"
            ]
          },
          "debug": true,
          "modules": false,
          "useBuiltIns": true
        }
      ],
      "react"
    ],
    "plugins": [
      "transform-object-rest-spread",
      "transform-flow-strip-types"
    ],
    "env": {
      "development": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-jsx-source"
        ]
      },
      "production": {
        "only": [
          "app"
        ],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements"
        ]
      },
      "test": {
        "plugins": [
          "transform-es2015-modules-commonjs"
        ]
      }
    }
  }
```

you can clone the [repo](https://github.com/andykenward/bob/tree/458508a7e3c50794e0430204aba0432a776151dd)

**Comment by andykenward** [comment]
You can see a travis-ci log [here](https://travis-ci.org/andykenward/bob/jobs/182849700)

**Comment by hzoo** [comment]
Oh yes! good catch and will fix.

**Comment by hzoo** [comment]
Should of looked at that more closely!!

https://github.com/babel/babel-preset-env/issues/68

**Comment by andykenward** [comment]
@hzoo that has fixed the import issue. But not the UglifyJS one.

```
ERROR in main.c6d5c804d7906153b78c.js from UglifyJs
SyntaxError: Unexpected token punc «}», expected punc «:» [main.c6d5c804d7906153b78c.js:561,18]
```

**Comment by hzoo** [comment]
Can make a new issue for that - also going to be hard to fix since not a lot of info from that or a repro step with minimal amount of code haha.

**Comment by andykenward** [comment]
Ok will do. Looking into it more myself at the moment.

**Comment by hzoo** [comment]
Cool if you figure out more make a new issue and we can figure it out (gotta go)

**Comment by andykenward** [comment]
The UglifyJs issue is to do with it not supporting es6 in the version used for webpack `2.1.0-beta.25`. 

So it will error out with it hits `=>` at the moment.

**Comment by hzoo** [comment]
Ah makes a lot of sense! Well then I can recommend trying out https://github.com/babel/babili 😄!! Babel minifier which does understand ES6+. It's still beta but we would appreciate the issues that you find

**Comment by andykenward** [comment]
Just a follow up to anyone who comes across this with Uglify and Webpack 2 issues.

As Webpack `2.2.1` comes with `"uglify-js": "^2.7.5",` it does not support ES6+. So if you target latest browsers with `babel-preset-env` that do support native ES6+ it won't work.

I have switched to using [`babili`](https://github.com/babel/babili) as @hzoo suggested to minify my code. But have gone with [`babili-webpack-plugin`](https://www.npmjs.com/package/babili-webpack-plugin) for theses [reasons](https://www.npmjs.com/package/babili-webpack-plugin#why)
