### ISSUE TITLE
Data issues

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#7]
~~Data can be wrong in https://github.com/babel/babel-preset-env/blob/master/src/plugins.js.~~

We're using https://kangax.github.io/compat-table/es6/ now

<img width="1316" alt="screen shot 2016-10-08 at 11 13 43 am" src="https://cloud.githubusercontent.com/assets/588473/19214029/58deebce-8d48-11e6-9004-ee3fbcb75d8b.png">

There is also the issue of bugs in babel, bugs in the implementation, incomplete implementations (it supports the basic test of a feature but not everything), etc. This will require a lot of work to figure out but shouldn't be too bad with testing/attention to detail.

Can also use https://github.com/sdkennedy/babel-preset-target

**Comment by fson** [comment]
I took a first stab at generating the data from ES compatibility table in #8.

**Comment by chicoxyzzy** [comment]
Hey! Compatibility table collaborator here! I just want you to know I will be working on having raw  data in a distinct npm package soon.

**Comment by hzoo** [comment]
We should figure out granularity

- some browsers implement under a flag: (compat-table has `flag, strict, etc`) - what are these?
- maybe the browser implements most of the feature (say 12/13) which covers most use cases etc.

**Comment by hzoo** [comment]
we'll need to make some PRs to `compat-table` as we go when we find issues/missing stuff

**Comment by DZuz14** [comment]
Any stuff a junior dev can work on? Will gladly help out with anything I can.

**Comment by hzoo** [comment]
One thing that we want to do (continually) is check that `data/plugins.json` is actually correct/accurate to both what's actually true (testing in browsers/node) as well as correct to kangax.github.io/compat-table/es6/

**Comment by hzoo** [comment]
We're using compat-table already so we can close this. The issue is just that the data might be not up or date or the logic incorrect but that's an ongoing effort
