### ISSUE TITLE
What is "loose" transformation?

### ISSUE THREAD

**Issue by miksago** [babel/babel-preset-env#76]
Hi! In the documentation you've written the following: 

> Enable "loose" transformations for any plugins in this preset that allow them.

Could you please tell me what "loose" transformations are? After a quick google, I found [this article](http://www.2ality.com/2015/12/babel6-loose-mode.html?m=1), which I think is what you're talking about, but I just wanted to get clarification!

Thanks for the awesome looking project! 

Yours, Em

**Comment by hzoo** [comment]
Cool thanks for asking! I'l update the docs to point to our docs on loose mode. (Actually maybe we don't have a specific page for that anymore...)

Example is http://babeljs.io/docs/plugins/transform-es2015-for-of/#options-loose

Yeah that article is good, maybe should just link to that (if you want to PR please go ahead).

Yeah it's just that we want to be spec compliant where possible but in some cases it results in either a lot of code or performance issues. There's also a spec mode for the opposite case.

**Comment by hzoo** [comment]
Going to close for now - If you have more questions you can ask here or join our http://slack.babeljs.io/ too

**Comment by tolu** [comment]
This article sheds more light:
http://2ality.com/2015/12/babel6-loose-mode.html
