### ISSUE TITLE
Drop support for older versions of Node

### ISSUE THREAD

**Issue by baer** [babel/babel-preset-env#85]
Node 0.10 / 0.12 is at EOL. When the main babel project drops support officially, we should as well

See: babel/babel#4315

**Comment by Kovensky** [comment]
To clarify: this means that, while babel, or the preset itself may not run on old Nodes, it can still be used to generate code to run in old Node.

**Comment by baer** [comment]
I just intended for this to mean 2 things:

1. We will no longer run CI against old Node versions
2. We will compile the `lib` directory down as little as possible (bootstrapping ftw!)

**Comment by hzoo** [comment]
Done in https://github.com/babel/babel-preset-env/pull/185 already, 2.0 branch
