### ISSUE TITLE
Auto detect for node

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#9]
https://github.com/babel/babel/pull/3476#issuecomment-213222405

> Would be super nice if it could just adhere to what's in the [`engines` field](https://github.com/sindresorhus/ava/blob/3a4fc998cb6d361cbc49d3864937c9b18c279764/package.json#L37) in package.json. That way you wouldn't have to specify anything manually.

Or just determine current node version before running?

**Comment by deepsweet** [comment]
> Or just determine current node version before running?

https://github.com/rtsao/babel-preset-es2015-node/blob/master/index.js

**Comment by hzoo** [comment]
yeah we can use `process.version` but we still need to specify whether you are compiling node or compiling for other environments

**Comment by rtsao** [comment]
What about a special value for node (e.g. `{node: "process"}`) which infers from process.version?

**Comment by AlicanC** [comment]
@rtsao great idea. We should support keywords in versions. #23 needs that too.

**Comment by shubheksha** [comment]
I'll work on this!

**Comment by hzoo** [comment]
Awesome - I'l try to merge something of https://github.com/babel/babel-preset-env/pull/19 first to fix merge conflicts

**Comment by hzoo** [comment]
@shubheksha still able to work on this? no rush though

**Comment by hzoo** [comment]
You can do what was in https://github.com/facebookincubator/create-react-app/pull/878 if you use a preset or use a local js file. If you use a package.json/babelrc you won't be able to use javascript in the config so we could have a hardcoded option for this.

so you can specify `node: "process"` which will be the same as `node: parseFloat(process.versions.node)`

And maybe `process` isn't the best option name for this?

**Comment by hzoo** [comment]
@shubheksha Let me know if you need any more context/help on this, or if someone else can take this too

**Comment by hzoo** [comment]
https://github.com/babel/babel-preset-env/issues/35

w/ `"node": "current"` or `"node": true`
