### ISSUE TITLE
Add Rest Spread Syntax Plugin for Node >= 6.8.1

### ISSUE THREAD

**Issue by joshperry** [babel/babel-preset-env#90]
Since these operators have been [supported in node](http://node.green/#rest-parameters) for awhile (and are also in the LTS release) it would be nice if targeting node versions that support this operator would use the [syntax plugin](https://www.npmjs.com/package/babel-plugin-syntax-object-rest-spread).

**Comment by joshperry** [comment]
So apparently I'm mistaken. It does support them for arrays, but not yet objects. My apologies.

**Comment by hzoo** [comment]
Yeah it's important for us to signal more in the future which features are actually experimental and which aren't so it's not as confusing - object rest/pread is stage-3 right now
