### ISSUE TITLE
Add a "target preset" option?

### ISSUE THREAD

**Issue by hzoo** [babel/babel-preset-env#91]
```js
{
  "presets": [
    "env", {
      "targetPreset": "experimental-stage-3" // default to latest like it is currently,
      "targets": {
        "browsers": ["last 2 versions"]
      },
      "exclude": ["transform-regenerator"],
    }
  ] 
}
```

TLDR - figure out how we should include stage-3 plugins.

---

Oh man naming is hard: basically there's a difference between the "target javascript" you want to write in. What is currently "targets" is the list of environments you support (why didn't I just call it "environments" when the preset is preset-env lol 🤔 ).

The values of this option could potentially be any year, latest, or stage 3 (basically the current official presets that we have). In reality I think the only ones we care about would be `latest` and `stage 3`. The reason why [we didn't add stage-3 earlier](https://github.com/babel/babel-preset-env#support-all-plugins-in-babel-that-are-considered-latest) was because I kept thinking about the latest spec rather than forgetting that at stage-3 browser vendors will start implementations. Many projects/companies choose to target stage-3 (and if you are doing lower without codemods or serious consideration of the consequences then there will be issues and that's why we have been discussing https://github.com/babel/babel/issues/4914 and others).

**Comment by hzoo** [comment]
For this we can just do https://github.com/babel/babel-preset-env/pull/113/files but explicitly include the plugins (but only enable them if the relevant option is specified). Maybe the option can just be `stage3: true` - otherwise we go back to babel 5 to have a `stage: 1` option although we just need to be clearer about what that actually means to users (stage 0 meaning it's just an idea that can change or be removed at any point).

**Comment by rtsao** [comment]
@hzoo My initial reason for not manually specifying the plugins in #113 was I didn't like the idea of having two sources of truth regarding which plugins were used in which preset. If this were abstracted out somehow, the list wouldn't need to be duplicated.
