### ISSUE TITLE
latest release (v1.1.0) breaks builds

### ISSUE THREAD

**Issue by ahmadnassri** [babel/babel-preset-env#94]
![image](https://cloud.githubusercontent.com/assets/183195/21163227/d2c6aca6-c15f-11e6-832b-dd237866e9c5.png)

**Comment by hzoo** [comment]
Yep thanks for reporting just released 1.1.1 (got a report in slack)! Let me know if it's good

**Comment by ahmadnassri** [comment]
seems like releases are being made with excessive speed, and followed by patches right after ... either some tests are lacking or can implement a release candidate strategy first? perhaps using Github's draft releases?

**Comment by hzoo** [comment]
We are discussing in slack (it is because we are using babel-register in tests and it imports the polyfill so even though we run node 0.10) it didn't catch it. Discussing what to do

**Comment by hzoo** [comment]
And the previous patches were that I didn't write good enough tests for that feature (will do in https://github.com/babel/babel-preset-env/issues/72)

**Comment by ahmadnassri** [comment]
@hzoo good to hear, also, still broken.

**Comment by hzoo** [comment]
Ok could you provide the information on how to debug? the Object.values issue should be fixed.

**Comment by ahmadnassri** [comment]
it's still building on some modules, i'll let it run through and try again the failed ones .. standby...

**Comment by ahmadnassri** [comment]
kicking the build cache solved it, back to normal now. thx.
